### ISSUE TITLE
Server Crash Caught exception from ShetiPhian-Core

### ISSUE THREAD

**Issue by Centros** [ShetiPhian/Localizations-and-Issues#123]
Hello so I was doing some updates for a personal mod pack on twitch. After I moved the mods over to the server and started it. everything was fine till the end it crashed when loading the world.

Checked The core, ender tanks and terraqueous all of them are at the latest for 1.11.2 so i'm not quite sure whats up.

anywho here is the full report hope to get a reply soon thanks.

Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/11/17 7:06 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ShetiPhian-Core (shetiphiancore)
Caused by: java.lang.NoSuchMethodError: shetiphian.core.internal.ConfigHandler.sync()V
	at shetiphian.core.internal.ConfigHandler.syncConfig(ConfigHandler.java:31)
	at shetiphian.core.internal.ConfigHandler.setupConfig(ConfigHandler.java:20)
	at shetiphian.core.internal.ProxyCommon.setupConfig(ProxyCommon.java:16)
	at shetiphian.core.ShetiPhianCore.preInit(ShetiPhianCore.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:100)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11569324728 bytes (11033 MB) / 12867469312 bytes (12271 MB) up to 12867469312 bytes (12271 MB)
	JVM Flags: 7 total; -Xmx12G -Xms12G -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2454 174 mods loaded, 174 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2454-universal.jar) 
	UCH	forge{13.20.1.2454} [Minecraft Forge] (forge-1.11.2-13.20.1.2454-universal.jar) 
	UCH	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCH	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCH	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	itemblacklist{1.3.0.13} [ItemBlacklist] (ItemBlacklist-1.11.2-1.3.0.13.jar) 
	UCH	jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar) 
	UCH	abyssalcraft{1.9.4.1} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.4.1.jar) 
	UCH	chisel{MC1.11.2-0.0.14.25} [Chisel] (Chisel-MC1.11.2-0.0.14.25.jar) 
	UCH	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCH	tconstruct{1.11.2-2.7.1.34} [Tinkers' Construct] (TConstruct-1.11.2-2.7.1.34.jar) 
	UCH	acintegration{1.6.1} [AbyssalCraft Integration] (AbyssalCraft Integration-1.11.2-1.6.1.jar) 
	UCH	actuallyadditions{1.11.2-r110} [Actually Additions] (ActuallyAdditions-1.11.2-r110.jar) 
	UCH	baubles{1.4.6} [Baubles] (Baubles-1.11-1.4.6.jar) 
	UCH	actuallybaubles{1.1.1} [Actually Baubles] (ActuallyBaubles-1.11.2-1.1.1.jar) 
	UCH	additionalbanners{1.4.0.32} [Additional Banners] (AdditionalBanners-1.11.2-1.4.0.32.jar) 
	UCH	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCH	alltheblocks{1.11.2-1.1.0} [All the Blocks] (alltheblocks-1.11.2-1.1.0.jar) 
	UCH	craftstudioapi{0.3.0-beta} [CraftStudio API] (CraftStudioAPI-universal-0.3.0.86-mc1.11.2-beta.jar) 
	UCH	quark{r1.2-93} [Quark] (Quark-r1.2-93b.jar) 
	UCH	cofhcore{4.2.8} [CoFH Core] (CoFHCore-1.11.2-4.2.8.16-universal.jar) 
	UCH	animania{1.3.6.1} [Animania] (animania-1.11.2-1.3.6.1.jar) 
	UCH	tammodized{0.9.2} [TamModized] (TamModized-1.11.2-0.9.2.jar) 
	UCH	aov{0.2.5} [Angel of Vengeance] (AoV-1.11.2-0.2.5.jar) 
	UCH	aquaculture{1.5.1} [Aquaculture] (Aquaculture-1.11.2-1.5.1.2.jar) 
	UCH	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCH	thedragonlib{1.11.2-3.3.0} [TheDragonLib] (thedragonlib-1.11.2-3.3.0.jar) 
	UCH	armorplus{1.11.2-10.8.0.1} [ArmorPlus] (armorplus-1.11.2-10.8.0.1.jar) 
	UCH	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.jar) 
	UCH	aromabackup{1.0} [AromaBackup] (AromaBackup-1.11-2.1.0.0.jar) 
	UCH	aromabackuprecovery{1.0} [AromaBackupRecovery] (AromaBackup-1.11-2.1.0.0.jar) 
	UCH	astralsorcery{1.4.5} [Astral Sorcery] (astralsorcery-1.4.5.jar) 
	UCH	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCH	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCH	base{2.1.0} [B.A.S.E] (base-1.11.2-2.1.0.jar) 
	UCH	bibliocraft{2.3.3} [BiblioCraft] (BiblioCraft[v2.3.3][MC1.11.2].jar) 
	UCH	bibliowoodsforestry{2.0} [BiblioWoodForestry] (BiblioWoods[Forestry][v2.0][MC1.11.2].jar) 
	UCH	natura{1.11.2-4.2.0.33} [Natura] (natura-1.11.2-4.2.0.33.jar) 
	UCH	bibliowoodsnatura{2.0} [BiblioWoodNatura] (BiblioWoods[Natura][v2.0][MC1.11.2].jar) 
	UCH	forestry{5.3.4.165} [Forestry] (forestry_1.11.2-5.3.4.165.jar) 
	UCH	binniecore{2.1.0.41} [Binnie Core] (binnie-mods-1.11.2-2.1.0.41.jar) 
	UCH	botany{2.1.0.41} [Binnie's Botany] (binnie-mods-1.11.2-2.1.0.41.jar) 
	UCH	extrabees{2.1.0.41} [Binnie's Extra Bees] (binnie-mods-1.11.2-2.1.0.41.jar) 
	UCH	extratrees{2.1.0.41} [Binnie's Extra Trees] (binnie-mods-1.11.2-2.1.0.41.jar) 
	UCH	genetics{2.1.0.41} [Binnie's Genetics] (binnie-mods-1.11.2-2.1.0.41.jar) 
	UCH	guideapi{1.11.2-2.1.4-56} [Guide-API] (Guide-API-1.11.2-2.1.4-56.jar) 
	UCH	bloodmagic{1.11-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.11-80.jar) 
	UCH	bloodarsenal{1.11.2-2.1.0-CUSTOM} [Blood Arsenal] (BloodArsenal-1.11.2-2.1.0-19.jar) 
	UCH	lazymodder{0.1} [Lazy Modder] (LazyModder-1.11-1.0.jar) 
	UCH	bloodbaubles{0.0} [Blood Baubles] (BloodBaubles-1.11-1.0.jar) 
	UCH	bookshelf{2.0.388} [Bookshelf] (Bookshelf-1.11.2-2.0.0.388.jar) 
	UCH	botania{r1.9-345} [Botania] (Botania r1.9-345.jar) 
	UCH	codechickenlib{3.0.0.298} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.298-universal.jar) 
	UCH	brandonscore{2.2.5} [Brandon's Core] (BrandonsCore-1.11.2-2.2.5.135-universal.jar) 
	UCH	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCH	chattimestamp{1.0.0} [ChatTimestamp] (chattimestamp-1.10.2-1.0.0.jar) 
	UCH	chickenchunks{2.3.1.68} [ChickenChunks] (ChickenChunks-1.11.2-2.3.1.68-universal.jar) 
	UCH	chiselsandbits{13.14} [Chisels & Bits] (chiselsandbits-13.14.jar) 
	UCH	chunkpregenerator{1.4} [Chunk Pregenerator] (Chunk Pregenerator V-1.11-1.4.1.jar) 
	UCH	clumps{2.0.0} [Clumps] (Clumps-2.0.0.jar) 
	UCH	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCH	craftingtweaks{7.1.9} [Crafting Tweaks] (CraftingTweaks_1.11.2-7.1.9.jar) 
	UCH	crafttweakerjei{1.0.2} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.26.jar) 
	UCH	crafttweaker{3.0.26} [Crafttweaker] (CraftTweaker-1.11.2-3.0.26.jar) 
	UCH	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.9.4 mc1.11.2.jar) 
	UCH	modcurrency{1.11.2-1.2.2} [Good Ol' Currency Mod] (Currency-1.11.2-1.2.2.jar) 
	UCH	customstartinggear{2.0.0} [Custom Starting Gear] (CustomStartingGear-1.11.2-2.0.0.7-universal.jar) 
	UCH	cyberware{alpha-0.2.10} [Cyberware] (cyberware-1.11.2-alpha-0.2.10.jar) 
	UCH	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.11.2-0.10.9.jar) 
	UCH	waila{1.8.22} [Waila] (Hwyla-1.8.22-B37_1.11.jar) 
	UCH	darkutils{1.2.0.147} [Dark Utilities] (DarkUtilities-1.11.2-1.2.0.147.jar) 
	UCH	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.5.2_1.11.2.jar) 
	UCH	props{2.5.2} [Decocraft] (Decocraft-2.5.2_1.11.2.jar) 
	UCH	eleccore{1.7.431} [ElecCore] (ElecCore-1.11-1.7.431.jar) 
	UCH	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.1x-1.4.8.jar) 
	UCH	discordintegration{3.0.4} [DiscordIntegration] (DiscordIntegration-mc1.11.2-3.0.4.jar) 
	UCH	thermalfoundation{2.2.5} [Thermal Foundation] (ThermalFoundation-1.11.2-2.2.5.16-universal.jar) 
	UCH	draconicevolution{2.2.5} [Draconic Evolution] (Draconic-Evolution-1.11.2-2.2.5.271-universal.jar) 
	UCH	storagedrawers{1.11.2-4.2.10} [Storage Drawers] (StorageDrawers-1.11.2-4.2.10.jar) 
	UCH	bitdrawers{0.41} [Drawers & Bits] (DrawersBits-1.11.2-0.41.jar) 
	UCH	dungeontactics{DT-0.12.5} [DungeonTactics] (DungeonTactics-1.11.2-0.12.5.jar) 
	UCH	elementaria{3.0.2} [Elementaria] (Elementaria 3.0.2.jar) 
	UCH	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.1.116-universal.jar) 
	UCE	shetiphiancore{3.4.8} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.8.jar) 
	UCE	endertanks{1.5.6} [EnderTanks] (endertanks-1.11.0-1.5.6.jar) 
	UCH	evilcraft{0.10.30} [EvilCraft] (EvilCraft-1.11.2-0.10.30.jar) 
	UCH	evilcraftcompat{1.0.0} [EvilCraft-Compat] (EvilCraft-1.11.2-0.10.30.jar) 
	UCH	extraalchemy{0.3.3.1-release} [Extra Alchemy] (extraalchemy-0.3.3.1-release.jar) 
	UCH	extrabitmanipulation{1.11.2-3.2.1} [Extra Bit Manipulation] (ExtraBitManipulation-1.11.2-3.2.1.jar) 
	UCH	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UCH	extrarails{1.2.1} [Extra Rails] (ExtraRails-1.11-1.2.1.jar) 
	UCH	extratweaker{0.4} [ExtraTweaker] (ExtraTweaker-1.11.2-0.4.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.6.5.jar) 
	UCH	zerocore{1.11.2-0.1.1.0} [Zero CORE] (zerocore-1.11.2-0.1.1.0.jar) 
	UCH	bigreactors{1.11.2-0.4.5.44} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.44.jar) 
	UCH	fairylights{2.1.1} [Fairy Lights] (fairylights-2.1.1-1.11.x.jar) 
	UCH	fastleafdecay{v15} [Fast Leaf Decay] (FastLeafDecay-v15.jar) 
	UCH	glass_shards{1.6.3} [Glass Shards] (glass_shards_mc1.11.2-1.6.3.jar) 
	UCH	gud_clear_jukebox{1.0.0.1} [Clear Jukebox] (gud_clear_jukebox-1.0.0.1.jar) 
	UCH	helpfixer{1.4+17} [HelpFixer] (HelpFixer-1.11-1.4+17.jar) 
	UCH	hopperducts{1.4.9.2} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.2.jar) 
	UCH	llibrary{1.7.7} [LLibrary] (llibrary-1.7.7-1.11.2.jar) 
	UCH	iceandfire{1.2.1} [Ice and Fire] (iceandfire-1.2.1.jar) 
	UCH	immersiveengineering{0.11-63} [Immersive Engineering] (ImmersiveEngineering-0.11-63.jar) 
	UCH	immersivepetroleum{1.1.3} [Immersive Petroleum] (immersivepetroleum-1.11.2-1.1.3.jar) 
	UCH	infernum{0.1.1} [Infernum] (infernum-0.1.1.1.jar) 
	UCH	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCH	ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar) 
	UCH	jehc{1.3.0} [Just Enough HarvestCraft] (jehc-1.11.2-1.3.1.jar) 
	UCH	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCH	journeymap{1.11.2-5.5.2} [JourneyMap] (journeymap-1.11.2-5.5.2.jar) 
	UCH	jaff{1.6.1_for_1.11.2} [Just a Few Fish] (JustAFewFish-1.6.1_for_1.11.2.jar) 
	UCH	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.0.6-1.11.2.jar) 
	UCH	levels{r1.2.8} [Levels] (Levels 2-1.11.2-r1.2.8.jar) 
	UCH	librarianlib{3.1.5} [LibrarianLib] (librarianlib-3.1.5.jar) 
	UCH	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (literalascension-1.11.2-1.0.2.2.jar) 
	UCH	login_shield{1.11.2-12-g3b6dbfe} [Login Shield] (Login_Shield-1.11.2-12-g3b6dbfe.jar) 
	UCH	magicbees{1.0} [MagicBees] (MagicBees-Beta-3.0.4.jar) 
	UCH	malisiscore{1.11.2-5.2.5} [MalisisCore] (malisiscore-1.11.2-5.2.5.jar) 
	UCH	malisisdoors{1.11.2-6.1.3} [MalisisDoors] (malisisdoors-1.11.2-6.1.3.jar) 
	UCH	minecolonies{1.11.2-0.8.4057} [MineColonies] (minecolonies-universal-1.11.2-0.8.4057.jar) 
	UCH	mtlib{@VERSION@} [MTLib] (MTLib-2.0.3.jar) 
	UCH	modtweaker{3.0.2} [Mod Tweaker] (modtweaker-3.0.2.jar) 
	UCH	morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus-1.11.2-3.2.14.jar) 
	UCH	mputils{1.3.10} [ModPack Utilities] (mputils-1.11.2-1.3.10.jar) 
	UCH	mpbasic{1.2.2} [ModPack Basic Tools] (mpbasic-1.11.2-1.2.2.jar) 
	UCH	mysticalagriculture{1.5.9} [Mystical Agriculture] (mysticalagriculture-1.11.2-1.5.9.jar) 
	UCH	mysticalagradditions{1.1.3} [Mystical Agradditions] (mysticalagradditions-1.11.2-1.1.3.jar) 
	UCH	botanicaladdons{2.3} [Natural Pledge] (NaturalPledge-r2.3.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCH	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCH	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCH	neid{1.5.4.1} [NotEnoughIDs] (NotEnoughIDs-1.5.4.1.jar) 
	UCH	getalltheseeds{1.11a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds! 1.11a.jar) 
	UCH	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCH	pamscookables{1.0} [Pam's Cookables] (pamscookables-1.11.2_1.0.jar) 
	UCH	plustic{5.2.1.2} [PlusTiC] (plustic-5.2.1.2.jar) 
	UCH	railsplus{1.0.0} [Rails Plus] (railsplus-1.0.1.jar) 
	UCH	rainboaks{1.0.2} [Rainbow Oak Trees] (RainbowOaks-1.11-1.0.2.jar) 
	UCH	thermalexpansion{5.2.7} [Thermal Expansion] (ThermalExpansion-1.11.2-5.2.7.30-universal.jar) 
	UCH	redstonearsenal{2.2.6} [Redstone Arsenal] (RedstoneArsenal-1.11.2-2.2.6.10-universal.jar) 
	UCH	refinedstorage{1.4.20} [Refined Storage] (refinedstorage-1.4.20.jar) 
	UCH	xreliquary{1.11.2-1.3.4.678} [Reliquary] (Reliquary-1.11.2-1.3.4.678.jar) 
	UCH	rftools{7.13} [RFTools] (rftools-1.1x-7.13.jar) 
	UCH	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.1x-1.6.8.jar) 
	UCH	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCH	runesofwizardry{1.11.2-0.8.2} [Runes of Wizardry] (Runes-of-Wizardry-1.11.2-0.8.2.jar) 
	UCH	rustic{0.3.13} [Rustic] (rustic-0.3.13.jar) 
	UCH	silentlib{2.2.6} [Silent Lib] (SilentLib-1.11.2-2.2.6-66.jar) 
	UCH	scalinghealth{1.2.2} [Scaling Health] (ScalingHealth-1.12-1.2.2-70.jar) 
	UCH	silentgems{2.4.7} [Silent's Gems] (SilentsGems-1.11.2-2.4.7-217.jar) 
	UCH	sgextraparts{1.3.3} [Silent's Gems: Extra Parts] (SGExtraParts-1.12-1.3.3-29.jar) 
	UCH	silentboss{1.5.0} [SilentBoss] (SilentBoss-1.5.0.jar) 
	UCH	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.11.2-2.0.0.jar) 
	UCH	storagetech{1.1} [Storage Tech] (StorageTech 1.1.jar) 
	UCE	terraqueous{1.3.17} [Terraqueous] (terraqueous-1.11.0-1.3.17.jar) 
	UCH	thermaldynamics{2.2.7} [Thermal Dynamics] (ThermalDynamics-1.11.2-2.2.7.16-universal.jar) 
	UCH	tinker_io{release 2.5.5c} [Tinker I/O] (tinker_io-1.11.2-release 2.5.5c.jar) 
	UCH	tinkertoolleveling{1.11.2-1.0.1.DEV.641b08f} [Tinkers Tool Leveling] (TinkerToolLeveling-1.11.2-1.0.1.jar) 
	UCH	tombstone{1.4.1} [Corail Tombstone] (tombstone-1.4.1-1.11.2.jar) 
	UCH	totemic{1.11.2-0.8.7} [Totemic] (Totemic-1.11.2-0.8.7.jar) 
	UCH	trashslot{7.4.8} [TrashSlot] (TrashSlot_1.11.2-7.4.8.jar) 
	UCH	vending{1.4.3.1} [Vending] (vending-1.11.2-1.4.3.1.jar) 
	UCH	vc{5.0.10-final} [ViesCraft] (ViesCraft-1.11.2-5.0.10-final.jar) 
	UCH	vctweaker{1.2} [ViesCraft Tweaker] (ViesCraftTweaker-1.11.2-1.2.4.jar) 
	UCH	wawla{2.4.0.231} [What Are We Looking At] (Wawla-1.11.2-2.4.0.231.jar) 
	UCH	waystones{3.0.17} [Waystones] (Waystones_1.11.2-3.0.17.jar) 
	UCH	worldlimiter{1.2.0} [World Limiter Mod] (worldlimiter-1.11.2-1.2.0.jar) 
	UCH	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	UCH	librarianliblate{3.1.5} [LibrarianLib Stage 2] (librarianlib-3.1.5.jar) 
	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
LibrarianLib Plugin (librarianlib-3.1.5.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
Extra Alchemy ASM (extraalchemy-0.3.3.1-release.jar)
  zabi.minecraft.extraalchemy.asm.PotionTransformer
LoadingPlugin (Quark-r1.2-93b.jar)
  vazkii.quark.base.asm.ClassTransformer
ItemPatchingLoader (ItemPhysic Full 1.4.9 mc1.11.2.jar)
  com.creativemd.itemphysic.ItemTransformer
AstralCore (astralsorcery-1.4.5.jar)
  
MalisisCorePlugin (malisiscore-1.11.2-5.2.5.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
llibrary (llibrary-1.7.7-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.298-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
LoadingPlugin (ChunkAnimator-MC1.11-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
CreativePatchingLoader (CreativeCore v1.9.4 mc1.11.2.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
SHLoadingPlugin (ScalingHealth-1.12-1.2.2-70.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
ViesCraftTweakerCore (ViesCraftTweaker-1.11.2-1.2.4.jar)
  se.gory_moon.vctweaker.asm.VCTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.jar)
  
CoFH Loading Plugin (CoFHCore-1.11.2-4.2.8.16-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.8.jar)
  shetiphian.core.asm.ClassTransformer
literalascension (literalascension-1.11.2-1.0.2.2.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
CTMCorePlugin (CTM-MC1.11.2-0.2.3.14.jar)
  team.chisel.ctm.client.asm.CTMTransformer
BookshelfLoadingPlugin (Bookshelf-1.11.2-2.0.0.388.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
Plugin (NotEnoughIDs-1.5.4.1.jar)
  ru.fewizz.neid.asm.Transformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Centros** [comment]
sorry actually it apparently was a problem with Item black list. I deleted all the configs and let it run to rewrite them and it fingered that mod instead :P removed it server started.
