### ISSUE TITLE
Sprinting causes crash 

### ISSUE THREAD

**Issue by Tschipp** [ShetiPhian/Localizations-and-Issues#188]
When sprinting, the client freezes and crashes.
Versions:
shetiphiancore-1.12.0-3.5.7
multistorage-1.12.0-1.4.10
forge-14.23.4.2705 (Recommended at time of writing)

Log:
```
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:212) ~[NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:865) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: java.lang.NoSuchFieldError: field_70165_t
	at shetiphian.asm.Hooks.entityRunParticles(Hooks.java:13) ~[ShetiPhian-ASM-1.12.0.jar:?]
	at net.minecraft.entity.Entity.createRunningParticles(Entity.java:1416) ~[Entity.class:?]
	at net.minecraft.entity.Entity.spawnRunningParticles(Entity.java:1410) ~[Entity.class:?]
	at net.minecraft.entity.Entity.onEntityUpdate(Entity.java:545) ~[Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:277) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.Entity.onUpdate(Entity.java:465) ~[Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2313) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:272) ~[EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:423) ~[EntityPlayerMP.class:?]
	at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:185) ~[NetHandlerPlayServer.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:212) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197) ~[NetworkSystem.class:?]
```

**Comment by ShetiPhian** [comment]
_field_70165_t_ is Entity.posX
Neither its public status or its SRG name should change within a Minecraft version, so it should be there and accessible.

And looking at some Forge patches they are using it still.
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/tileentity/MobSpawnerBaseLogic.java.patch#L8

I have no clue what caused the error. (by rights spawners should also be crashing the game)
Was this a one off, or does it happen often?
Do you have other mods installed?

**Comment by Tschipp** [comment]
Interesting... It happens every time I sprint... mind you, this was happening in a dev environment, the only other mods that were installed was my mod, CarryOn and gamestages (a dependency of CarryOn). I also find it weird, since it seems like an issue that would have been discovered and fixed a long time ago... I‘ll do some testing in a clean install and get back to you

**Comment by ShetiPhian** [comment]
In a dev environment embedded jars must be extracted after the mods have been processed into the naming snapshot being used.

To stop the asm jar from being extracted:
Inside the meta-inf folder from ShetiPhianCore, if you delete the 'ContainedDeps: shetiphian-asm.jar' from the manifest.mf file (might be able to delete the whole meta-inf folder)

The asm jar is not critical and doesn't need to load.

**Comment by Tschipp** [comment]
Ah I see, I‘ll try that

**Comment by Shovinus** [comment]
I also had this issue.

**Comment by ShetiPhian** [comment]
I'll have to see if there is a way to work around this.
Either way though I'll wrap it in an error handler so it doesn't crash.
