### ISSUE TITLE
Cloud workbench crash 

### ISSUE THREAD

**Issue by Beyondall01** [ShetiPhian/Localizations-and-Issues#213]
When you use it. It crash the game. 

Here the crash report;

[17:27:51] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:27:51] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:27:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:27:52] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2811 for Minecraft 1.12.2 loading
[17:27:52] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_211, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_211
[17:27:52] [main/INFO] [FML]: Searching C:\Users\henry\AppData\Roaming\.minecraft\mods for mods
[17:27:52] [main/WARN] [FML]: The coremod shetiphian.asm.TweakPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[17:27:52] [main/WARN] [FML]: The coremod ShetiPhian-ASM (shetiphian.asm.TweakPlugin) is not signed!
[17:27:52] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:27:52] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:27:52] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:27:52] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:27:52] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:27:56] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:27:56] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:27:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:27:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:27:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:27:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:27:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:27:57] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:27:58] [main/INFO] [ShetiPhian-ASM]: Attempting: Injection of Run Particle Override into Entity.createRunningParticles
[17:27:58] [main/INFO] [ShetiPhian-ASM]: Searching for: Entity.createRunningParticles (func_174808_Z)
[17:27:58] [main/INFO] [ShetiPhian-ASM]: Found Method: Entity.createRunningParticles
[17:27:58] [main/INFO] [ShetiPhian-ASM]: Injecting: Run Particle Override
[17:27:59] [Client thread/INFO] [minecraft/Minecraft]: Setting user: Drake
[17:28:07] [Client thread/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[17:28:07] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[17:28:09] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 71374176 bytes (68 MB) / 265945088 bytes (253 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13447 Compatibility Profile Context 16.300.2701.0' Renderer: 'AMD Radeon(TM) R6 Graphics'
[17:28:09] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2811 Initialized
[17:28:09] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[17:28:10] [Client thread/INFO] [FML]: Replaced 1036 ore ingredients
[17:28:11] [Client thread/INFO] [FML]: Searching C:\Users\henry\AppData\Roaming\.minecraft\mods for mods
[17:28:12] [Thread-3/INFO] [FML]: Using alternative sync timing : 200 frames of Display.update took 2068365787 nanos
[17:28:15] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[17:28:16] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, terraqueous, shetiphiancore] at CLIENT
[17:28:16] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, terraqueous, shetiphiancore] at SERVER
[17:28:18] [Client thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Terraqueous, FMLFileResourcePack:ShetiPhian-Core
[17:28:18] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[17:28:18] [Client thread/INFO] [FML]: Found 1212 ObjectHolder annotations
[17:28:18] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[17:28:18] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[17:28:19] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:28:19] [Forge Version Check/INFO] [forge.VersionCheck]: [shetiphiancore] Starting version check at https://gist.githubusercontent.com/ShetiPhian/5a4332ca6221ae61ab3c6d531a989f21/raw/ShetiPhianCore
[17:28:20] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[17:28:20] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: OUTDATED Target: 14.23.5.2836
[17:28:20] [Forge Version Check/INFO] [forge.VersionCheck]: [terraqueous] Starting version check at https://gist.githubusercontent.com/ShetiPhian/5a4332ca6221ae61ab3c6d531a989f21/raw/Terraqueous
[17:28:34] [Client thread/INFO] [FML]: Applying holder lookups
[17:28:34] [Client thread/INFO] [FML]: Holder lookups applied
[17:28:34] [Client thread/INFO] [FML]: Applying holder lookups
[17:28:34] [Client thread/INFO] [FML]: Holder lookups applied
[17:28:34] [Client thread/INFO] [FML]: Applying holder lookups
[17:28:34] [Client thread/INFO] [FML]: Holder lookups applied
[17:28:34] [Client thread/INFO] [FML]: OBJLoader: Domain terraqueous has been added.
[17:28:34] [Client thread/INFO] [FML]: Applying holder lookups
[17:28:34] [Client thread/INFO] [FML]: Holder lookups applied
[17:28:34] [Client thread/INFO] [FML]: Injecting itemstacks
[17:28:34] [Client thread/INFO] [FML]: Itemstack injection complete
[17:28:37] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[17:28:37] [Thread-5/INFO] [minecraft/SoundManager]: Initializing LWJGL OpenAL
[17:28:37] [Thread-5/INFO] [minecraft/SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:28:38] [Thread-5/INFO] [minecraft/SoundManager]: OpenAL initialized.
[17:28:38] [Sound Library Loader/INFO] [minecraft/SoundManager]: Sound engine started
[17:28:45] [Client thread/INFO] [FML]: OBJLoader.Parser: command 's' (model: 'terraqueous:models/block/doodads/doodad_branch.obj') is not currently supported, skipping. Line: 71 's off'
[17:28:49] [Client thread/INFO] [FML]: Max texture size: 16384
[17:28:58] [Client thread/INFO] [minecraft/TextureMap]: Created: 1024x512 textures-atlas
[17:29:03] [Client thread/INFO] [FML]: Applying holder lookups
[17:29:03] [Client thread/INFO] [FML]: Holder lookups applied
[17:29:04] [Client thread/INFO] [shetiphiancore]: Loading GuideFile: /assets/shetiphianguide/terraqueous.json
[17:29:04] [Client thread/INFO] [FML]: Injecting itemstacks
[17:29:04] [Client thread/INFO] [FML]: Itemstack injection complete
[17:29:05] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 6 mods
[17:29:05] [Client thread/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[17:29:05] [Client thread/INFO] [mojang/NarratorWindows]: Narrator library for x64 successfully loaded
[17:29:46] [Server thread/INFO] [minecraft/IntegratedServer]: Starting integrated minecraft server version 1.12.2
[17:29:46] [Server thread/INFO] [minecraft/IntegratedServer]: Generating keypair
[17:29:46] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[17:29:47] [Server thread/INFO] [FML]: Applying holder lookups
[17:29:47] [Server thread/INFO] [FML]: Holder lookups applied
[17:29:47] [Server thread/INFO] [FML]: Loading dimension 0 (uiu) (net.minecraft.server.integrated.IntegratedServer@122738ff)
[17:29:48] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[17:29:50] [Server thread/INFO] [FML]: Loading dimension -1 (uiu) (net.minecraft.server.integrated.IntegratedServer@122738ff)
[17:29:50] [Server thread/INFO] [FML]: Loading dimension 1 (uiu) (net.minecraft.server.integrated.IntegratedServer@122738ff)
[17:29:50] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for level 0
[17:29:51] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 4%
[17:29:52] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 7%
[17:29:53] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 11%
[17:29:54] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 16%
[17:29:55] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 21%
[17:29:56] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 27%
[17:29:57] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 33%
[17:29:58] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 39%
[17:29:59] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 45%
[17:30:00] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 51%
[17:30:01] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 57%
[17:30:02] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 64%
[17:30:03] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 71%
[17:30:04] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 80%
[17:30:05] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 88%
[17:30:06] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 95%
[17:30:07] [Server thread/INFO] [FML]: Unloading dimension -1
[17:30:07] [Server thread/INFO] [FML]: Unloading dimension 1
[17:30:07] [Server thread/INFO] [minecraft/IntegratedServer]: Changing view distance to 15, from 10
[17:30:10] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
[17:30:10] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[17:30:10] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 6 mods : minecraft@1.12.2,FML@8.0.99.99,forge@14.23.5.2811,shetiphiancore@3.5.9,terraqueous@1.4.16,mcp@9.42
[17:30:10] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[17:30:10] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[17:30:10] [Server thread/INFO] [minecraft/PlayerList]: Drake[local:E:d6697ae8] logged in with entity id 1148 at (22.5, 68.0, -55.5)
[17:30:10] [Server thread/INFO] [minecraft/MinecraftServer]: Drake joined the game
[17:30:12] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[17:30:12] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'uiu'/overworld
[17:30:13] [pool-3-thread-1/WARN] [mojang/YggdrasilMinecraftSessionService]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@fceec9c[id=b150f254-e798-36bc-9e37-b04180539289,name=Drake,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:60) [YggdrasilMinecraftSessionService$1.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:57) [YggdrasilMinecraftSessionService$1.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [guava-21.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:170) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.client.Minecraft.func_181037_M(Minecraft.java:3001) [bib.class:?]
	at net.minecraft.client.resources.SkinManager$3.run(SourceFile:110) [cex$3.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[17:30:17] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 7113ms behind, skipping 142 tick(s)
[17:30:30] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2145ms behind, skipping 42 tick(s)
[17:30:51] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2273ms behind, skipping 45 tick(s)
[17:31:54] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[17:31:54] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[17:31:54] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[17:31:54] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'uiu'/overworld
[17:31:55] [Server thread/INFO] [FML]: Unloading dimension 0
[17:31:55] [Server thread/INFO] [FML]: Applying holder lookups
[17:31:55] [Server thread/INFO] [FML]: Holder lookups applied
[17:31:58] [Client thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.NoSuchMethodError: net.minecraft.client.gui.recipebook.GuiRecipeBook.func_191856_a(IILnet/minecraft/client/Minecraft;ZLnet/minecraft/inventory/Container;Lnet/minecraft/inventory/InventoryCrafting;)V
	at shetiphian.terraqueous.client.gui.GuiCraftingContainer.func_73866_w_(GuiCraftingContainer.java:35) ~[GuiCraftingContainer.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018) ~[bib.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501) ~[FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322) ~[FMLCommonHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
	at shetiphian.terraqueous.common.block.BlockCrafting.openGui(BlockCrafting.java:286) ~[BlockCrafting.class:?]
	at shetiphian.terraqueous.common.block.BlockCrafting.func_180639_a(BlockCrafting.java:261) ~[BlockCrafting.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423) ~[bsa.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[17:31:59] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 5/1/19 5:31 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.client.gui.recipebook.GuiRecipeBook.func_191856_a(IILnet/minecraft/client/Minecraft;ZLnet/minecraft/inventory/Container;Lnet/minecraft/inventory/InventoryCrafting;)V
	at shetiphian.terraqueous.client.gui.GuiCraftingContainer.func_73866_w_(GuiCraftingContainer.java:35)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501)
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at shetiphian.terraqueous.common.block.BlockCrafting.openGui(BlockCrafting.java:286)
	at shetiphian.terraqueous.common.block.BlockCrafting.func_180639_a(BlockCrafting.java:261)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at shetiphian.terraqueous.client.gui.GuiCraftingContainer.func_73866_w_(GuiCraftingContainer.java:35)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501)
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:112)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at shetiphian.terraqueous.common.block.BlockCrafting.openGui(BlockCrafting.java:286)
	at shetiphian.terraqueous.common.block.BlockCrafting.func_180639_a(BlockCrafting.java:261)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Drake'/1148, l='MpServer', x=16.17, y=187.00, z=-79.45]]
	Chunk stats: MultiplayerChunkCache: 928, 928
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (20,64,-60), Chunk: (at 4,4,4 in 1,-4; contains blocks 16,0,-64 to 31,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 2005 game time, 2005 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 13 total; [EntitySquid['Squid'/36946, l='MpServer', x=10.70, y=62.05, z=-95.20], EntitySquid['Squid'/36947, l='MpServer', x=18.83, y=62.60, z=-88.45], EntitySquid['Squid'/36948, l='MpServer', x=18.55, y=59.97, z=-83.66], EntitySquid['Squid'/36949, l='MpServer', x=15.74, y=60.44, z=-95.08], EntityCoconut['Coconut'/37475, l='MpServer', x=14.50, y=76.82, z=-74.50], EntityCoconut['Coconut'/33661, l='MpServer', x=3.30, y=76.63, z=-53.40], EntityPlayerSP['Drake'/1148, l='MpServer', x=16.17, y=187.00, z=-79.45], EntityZombie['Zombie'/38783, l='MpServer', x=90.50, y=33.00, z=-112.50], EntityBat['Bat'/38788, l='MpServer', x=56.50, y=22.00, z=-58.50], EntitySquid['Squid'/27040, l='MpServer', x=16.35, y=62.17, z=-101.10], EntitySquid['Squid'/31456, l='MpServer', x=13.31, y=62.16, z=-100.00], EntitySquid['Squid'/31459, l='MpServer', x=8.50, y=61.85, z=-96.49], EntitySquid['Squid'/31460, l='MpServer', x=14.46, y=61.02, z=-97.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 306380680 bytes (292 MB) / 849530880 bytes (810 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2811 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                          | Signature                                |
	|:------ |:-------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                   | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                   | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2811.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2811 | forge-1.12.2-14.23.5.2811.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | shetiphiancore | 3.5.9        | shetiphiancore-1.12.0-3.5.9.jar | None                                     |
	| LCHIJA | terraqueous    | 1.4.16       | terraqueous-1.12.0-1.4.16.jar   | None                                     |

	Loaded coremods (and transformers): 
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13447 Compatibility Profile Context 16.300.2701.0' Renderer: 'AMD Radeon(TM) R6 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2811
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R6 Graphics GL version 4.5.13447 Compatibility Profile Context 16.300.2701.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G
[17:31:59] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\henry\AppData\Roaming\.minecraft\crash-reports\crash-2019-05-01_17.31.58-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Beyondall01** [comment]
https://hastebin.com/

**Comment by Beyondall01** [comment]
https://pastebin.com/QB8PZrAj

**Comment by ShetiPhian** [comment]
I was originally thinking mod conflict, but there is no other mods, and with those same version I also get the error. (which points to a missing method outside of my code)
This is likely due to my development environment using an extremely old Forge build, and the method is no longer available.
I'm updating now.

**Comment by ShetiPhian** [comment]
Lost support for 1.12.0 and 1.12.1 but most will be on 1.12.2 and the previous build works fine on the older versions (also no new features will be added in 1.12 anyway)

Here is a test build, it appears to be working:
http://www.mediafire.com/file/kjs7sjzcrtvg3y1/terraqueous-1.12.2-1.4.17.jar/file

**Comment by Beyondall01** [comment]
When I find a bug or a problem with a mod I test the mod in question alone
with no other, so I can be clear wither the problem is a mod and mod
compatibility problem or a other thing. So I can report it to the devps.
Thanks for your respons and love the mod you and your team have made 😁👍

**Comment by ShetiPhian** [comment]
Build now on Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2710018
