### ISSUE TITLE
Platformer crash

### ISSUE THREAD

**Issue by djmattyg007** [ShetiPhian/Localizations-and-Issues#253]
I inserted an iron ingot into one of the slots on the left side of the platformer, and the game crashed. Here's the stack trace I got:

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/1/20 11:52 PM
Description: mouseReleased event handler

java.lang.ClassCastException: net.minecraft.item.Item cannot be cast to net.minecraft.item.BlockItem
	at shetiphian.platforms.common.tileentity.TileEntityPlatFormer.setGhostSlot(TileEntityPlatFormer.java:293) ~[?:1.6.1] {re:classloading}
	at shetiphian.platforms.common.inventory.ContainerPlatFormer.func_184996_a(ContainerPlatFormer.java:133) ~[?:1.6.1] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:374) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:503) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseReleased(ContainerScreen.java:473) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:88) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$14131/1878254380.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:86) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$14095/459130821.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$10390/1296293976.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:296) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:946) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:itlt:CustomWindowTitle,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:itlt:CustomWindowTitle,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.36.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/768647376.call(Unknown Source) [forge-1.15.2-31.2.36.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at shetiphian.platforms.common.tileentity.TileEntityPlatFormer.setGhostSlot(TileEntityPlatFormer.java:293)
	at shetiphian.platforms.common.inventory.ContainerPlatFormer.func_184996_a(ContainerPlatFormer.java:133)
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:374)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:503)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseReleased(ContainerScreen.java:473)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:88)
	at net.minecraft.client.MouseHelper$$Lambda$14131/1878254380.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: shetiphian.platforms.client.gui.GuiPlatFormer
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:86)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$14095/459130821.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$10390/1296293976.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['djmattyg007'/275, l='MpServer', x=-1025.65, y=64.00, z=1532.64]]
	Chunk stats: Client Chunk Cache: 841, 576
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -7346597134139994231
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-64,63,-256), Chunk: (at 0,3,0 in -4,-16; contains blocks -64,0,-256 to -49,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 59642431 game time, 11664 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/768647376.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1063341720 bytes (1014 MB) / 3841458176 bytes (3663 MB) up to 3841458176 bytes (3663 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.36.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.36
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		glasscutter-1.0.1-1.15.2.jar Glasscutter {glasscutter@1.0.1 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		areas_1.15-1.0.jar Areas {areas@1.0 DONE}
		DeathCounter-1.15.2-1.2.0.jar Death Counter {deathcounter@1.2.0 DONE}
		ExtendedCrafting-1.15.2-2.0.6.jar Extended Crafting {extendedcrafting@2.0.6 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		EditSign-1.15.2-2.1.0+1.jar Edit Sign {edit_sign@2.1.0+1 DONE}
		ChineseWorkshop-1.15.2-2.5.1.jar ChineseWorkshop {chineseworkshop@2.5.1 DONE}
		ProjectE-1.15.2-PE1.0.4.jar ProjectE {projecte@1.0.4 DONE}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		SilentMechanisms-1.15.2-0.8.0+59.jar Silent's Mechanisms {silents_mechanisms@0.8.0+59 DONE}
		IronJetpacks-1.15.2-3.0.3.jar Iron Jetpacks {ironjetpacks@3.0.3 DONE}
		ForgeEndertech-1.15.2-6.0.4.0-build.0044.jar Forge Endertech {forgeendertech@6.0.4.0 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		globaldatapack-1.15.2-1.3.jar Dark Roleplay - Global Datapacks {globaldatapack@1.15.2-0.1.0 DONE}
		Powah-1.15.2-1.1.15.jar Powah {powah@1.1.15 DONE}
		ftb-gui-library-1.0.0.14.jar FTB GUI Library {ftbguilibrary@1.0.0.14 DONE}
		culinaryconstruct-FORGE-1.15.2-2.0.0.2.jar Culinary Construct {culinaryconstruct@FORGE-1.15.2-2.0.0.2 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		buildinggadgets-3.4.0.jar Building Gadgets {buildinggadgets@3.4.0 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		ftb-teams-1.0.0.5.jar FTB Teams {ftbteams@1.0.0.5 DONE}
		shetiphiancore-1.15-3.7.4.jar ShetiPhian-Core {shetiphiancore@3.7.4 DONE}
		MoreMekanismOres-1.15.2-1.0.5.jar More Mekanism Ores {mmko@1.15.2-1.0.5 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		DustrialDecor-0.2.1.jar 'Dustrial Decor' {dustrial_decor@0.2.0 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Beekeeper-1.15.1-1.0.0.0.jar Beekeeper {bk@1.0.0.0 DONE}
		Lollipop-1.15.2-1.0.16.jar Lollipop {lollipop@1.0.16 DONE}
		mcw-trapdors-1.0.0fix-mc1.15.2.jar Macaw's Trapdoors {mcwtrpdoors@1.0.0 DONE}
		SilentGear-1.15.2-1.11.3+160.jar Silent Gear {silentgear@1.11.3+160 DONE}
		fairylights-3.0.9-1.15.2.jar Fairy Lights {fairylights@3.0.9 DONE}
		simplybackpacks-1.15.2-1.4.11.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.11 DONE}
		pamhc2foodextended-1.15.2-1.0.0.jar Pam's HarvestCraft 2 Food Extended {pamhc2foodextended@version DONE}
		RedstoneExtras-1.15.1-1.0.0.3.jar Easy Redstone Extras {rsx@1.0.0.3 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		Botania-r1.15-388.jar Botania {botania@r1.15-388 DONE}
		managear-1.15.2-1.2.0.jar Mana Gear {managear@1.15.2-1.2.0 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		carrotslib-mc1.15.2-2.5.jar Carrots Lib {carrots@2.5.0 DONE}
		vanillafoodpantry-mc1.15.2-5.5.jar Vanilla Food Pantry {vanillafoodpantry@5.5.0 DONE}
		collective-1.15.2-1.39.jar Collective {collective@1.39 DONE}
		camera-1.6.9.jar Camera Mod {camera@1.6.9 DONE}
		extlights-2.1.jar Extended Lights {extlights@2.1 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		TorchBandolier-1.15.2-1.4.0+8.jar Torch Bandolier {torchbandolier@1.4.0+8 DONE}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 DONE}
		xercapaint-1.15.2-2.1.jar Joy of Painting {xercapaint@1.15.2-2.1 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		neoncraft-1.1.jar Neon Craft {neoncraft@1.1 DONE}
		buildersaddition-20200617b.jar Builders Crafts & Addition {buildersaddition@20200617b DONE}
		mcws-roofs-1.15.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		Reeves'sFurnitureMod-1.8-1.15.2.jar Reeves's Furniture Mod {reevess_furniture_mod@1.8 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		trashcans-1.0.3-mc1.15.jar Trash Cans {trashcans@1.0.3 DONE}
		AdChimneys-1.15.2-5.0.7.0-build.0047.jar Advanced Chimneys {adchimneys@5.0.7.0 DONE}
		CobbleForDays-1.1.3.jar Cobble For Days {cobblefordays@1.1.3 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CodeChickenLib-1.15.2-3.3.1.379-universal.jar CodeChicken Lib {codechickenlib@3.3.1.379 DONE}
		Kiwi-1.15.2-2.8.2.jar Kiwi {kiwi@2.8.2 DONE}
		ChessMod-1.15.2-0.606.jar Chess Mod {chessmod@1.15.2-0.606 DONE}
		simply_trophies-2.0-1.15.2.jar Simple Trophies {simple_trophies@2.0-1.15.2 DONE}
		doubledoors_1.15-2.1.jar Double Doors {doubledoors@2.1 DONE}
		Cucumber-1.15.2-3.0.9.jar Cucumber Library {cucumber@3.0.9 DONE}
		torchslabmod-1.15.2_v1.7.0.jar Torch Slab Mod {torchslabmod@1.7.0 DONE}
		pamhc2trees-1.15.2-1.0.7.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		EquipmentTooltips-1.15.2-1.4.3+14.jar Equipment Tooltips {equipmenttooltips@1.4.3+14 DONE}
		Floocraft 1.15.2-1.11.0.jar Floocraft {floocraftft@1.11.0 DONE}
		mermaidtail-1.4.jar Mermaid Tail Mod {mermaidtail@1.15.2-1.4.0 DONE}
		treeharvester_1.15-1.3.jar Tree Harvester {treeharvester@1.3 DONE}
		item-filters-2.2.0.15.jar Item Filters {itemfilters@2.2.0.15 DONE}
		platforms-1.15-1.6.1.jar Platforms {platforms@1.6.1 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		JEIEnchantmentInfo-1.16.1-1.2.0.jar JEI Enchantment Info {jeienchantmentinfo@1.16.1-1.2.0 DONE}
		jei-professions-1.0.0-1.15.2.jar JEI Professions {jeiprofessions@1.0.0 DONE}
		TPMod-1.15.2_1.1.1.jar Toilet Paper Mod {tpmod@1.1.1 DONE}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 DONE}
		invtweaks-1.15.2-2.0.9.jar Inventory Tweaks Renewed {invtweaks@1.15.2-2.0.9 DONE}
		extraboats-1.3.6-1.15.2.jar Extra Boats {extraboats@1.3.6 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		WallpaperCraft-1.15.2-1.2.2.jar Wallpapercraft {wallpapercraft@1.2.2 DONE}
		Clumps-5.0.2.6.jar Clumps {clumps@5.0.2.6 DONE}
		light-overlay-4.7.1.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		comforts-FORGE-1.15.2-2.0.0.4.jar Comforts {comforts@FORGE-1.15.2-2.0.0.4 DONE}
		appliedenergistics2-7.0.2.jar Applied Energistics 2 {appliedenergistics2@7.0.2 DONE}
		tumbleweed-1.15-0.4.8.jar Tumbleweed {tumbleweed@1.15-0.4.8 DONE}
		decorative_blocks-1.15.2-1.7.jar Decorative Blocks {decorative_blocks@1.7 DONE}
		BotanyPots-1.15.2-2.0.27.jar BotanyPots {botanypots@2.0.27 DONE}
		AdHooks-1.15.2-5.1.0.0-build.0046.jar Advanced Hook Launchers {adhooks@5.1.0.0 DONE}
		curioofundying-FORGE-1.15.2-3.0.jar Curio of Undying {curioofundying@FORGE-1.15.2-3.0 DONE}
		Coins-1.15.2-1.0.1.jar Coins {coins@1.0.1 DONE}
		pneumaticcraft-repressurized-1.15.2-1.4.4-64.jar PneumaticCraft: Repressurized {pneumaticcraft@1.15.2-1.4.4-64 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.1.7.jar McJtyLib {mcjtylib@1.15-4.1.7 DONE}
		rftoolsbase-1.15-1.1.6.jar RFToolsBase {rftoolsbase@1.15-1.1.6 DONE}
		xnet-1.15-2.1.10.jar XNet {xnet@1.15-2.1.10 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		passiveendermen_1.15.2-1.2.jar Passive Endermen {passiveendermen@1.2 DONE}
		EnderStorage-1.15.2-2.5.0.151-universal.jar EnderStorage {enderstorage@1.15.2-2.5.0.151 DONE}
		CraftTweaker-1.15.2-6.0.0.40.jar CraftTweaker {crafttweaker@6.0.0.40 DONE}
		ftb-chunks-1.1.0.15.jar FTB Chunks {ftbchunks@1.1.0.15 DONE}
		entityinfo_1.15-1.2.jar Entity Information {entityinfo@1.2 DONE}
		forge-1.15.2-31.2.36-universal.jar Forge {forge@31.2.36 DONE}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 DONE}
		Ceramics-1.15.2-1.4.0.jar Ceramics {ceramics@1.15.2-1.4.0 DONE}
		VendingMachine-1.15.1-1.0.0.1.jar Vending Machine {vm@1.0.0.1 DONE}
		xercamusic-1.15.2-2.1.jar Xerca's Music Maker Mod {xercamusic@1.15.2-2.1 DONE}
		immersiveposts-1.15.2-2.1.0.jar Immersive Posts {immersiveposts@2.1.0 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		colouredchat-1.15.1-1.4.5.jar ColouredChat {colouredchat@1.15.1-1.4.5 DONE}
		forge-1.15.2-31.2.36-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b DONE}
		rftoolsutility-1.15-2.1.9.jar RFToolsUtility {rftoolsutility@1.15-2.1.9 DONE}
		itlt-1.15.2-1.0.3.jar It's the little things {itlt@1.0.3 DONE}
		theoneprobe-1.15-2.0.7.jar The One Probe {theoneprobe@1.15-2.0.7 DONE}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 DONE}
		ImmersiveEngineering-1.15.2-3.2.0-114.jar Immersive Engineering {immersiveengineering@1.15.2-3.2.0-114 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		gates-1.6.jar Gates {gates@1.6 DONE}
		ceilingtorch-1.15.2-v1.7.jar Ceiling Torch {ceilingtorch@v1.7 DONE}
		omgourd-1.15.2-0.1.0b.jar Oh My Gourd {omgourd@0.4.0b DONE}
		rftoolsbuilder-1.15-2.1.8.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.8 DONE}
		paintings-1.15.2-7.0.0.0.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE}
		pamhc2foodcore-1.15.2-1.0.9.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		ftb-backups-2.1.0.2.jar FTB Utilities: Backups {ftbbackups@2.1.0.2 DONE}
		cyclepaintings_1.15-1.3.jar Cycle Paintings {cyclepaintings@1.3 DONE}
		FastWorkbench-1.15.2-3.1.1.jar FastWorkbench {fastbench@3.1.1 DONE}
		polymorph-FORGE-1.15.2-0.10.jar Polymorph {polymorph@FORGE-1.15.2-0.10 DONE}
		multibeds-1.15-1.6.3.jar Multi-Beds {multibeds@1.6.3 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		FluxNetworks-1.15.2-5.0.3-4.jar Flux Networks {fluxnetworks@1.15.2-5.0.3-4 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.15.2-1.1.2.jar Engineer's Decor {engineersdecor@1.1.2 DONE}
		Aquaculture-1.15.2-2.0.16.jar Aquaculture 2 {aquaculture@1.15.2-2.0.16 DONE}
		SilentGems-1.15.2-3.6.2+98.jar Silent's Gems 3 {silentgems@3.6.2+98 DONE}
		refinedstorageaddons-0.6.3.jar Refined Storage Addons {refinedstorageaddons@0.6.3 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		badcreepernbb-1.1.0.jar BadCreeperNoBoomBoom {badcreepernbb@1.1.0 DONE}
	Kiwi Modules: 
		chineseworkshop:blocks
		chineseworkshop:debug_stick
		chineseworkshop:decorations
		chineseworkshop:materials
		chineseworkshop:retexture
		kiwi:contributors
		kiwi:data
	Patchouli open book context: n/a
	Launched Version: forge-31.2.36
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
```

**Comment by ShetiPhian** [comment]
I must have missed a change, those slots where set to only accept blocks.

**Comment by ShetiPhian** [comment]
New build is up.
https://www.curseforge.com/minecraft/mc-mods/platforms/files/all

**Comment by djmattyg007** [comment]
Wow, thank you so much for the fast response!
