### ISSUE TITLE
Platforms: Incompatibility with Render Reigons

### ISSUE THREAD

**Issue by GradiusLover2000** [ShetiPhian/Localizations-and-Issues#255]
Hiya, this is christhefennec from curseforge, I finally figured out what kept spamming my log with opengl error 1281.

Whenever I run your Platforms mod with ShetiPhian Core with Optifine's Render Regions turned ON, this happens.  If I turn Render Regions OFF, the issue goes away.  It does not matter what other mods are loaded at the time (I'm sure even you can reproduce it)

Maybe there's a way you can fix it?  If not that's a bummer, hopefully Optifine will fix it down the line.

**Comment by ShetiPhian** [comment]
The way most models are done now, you control what gets rendered but not how, rendering is done by the render engine itself.
At setup the loader instructs the model to provide a list of needed texture names, then a list of other needed models. These items are then loaded.
At time of render the render engine gets a list of baked quads from the model and does all the rendering itself.
BakedQuads are just information used by the renderer; numbers indicating where each corner is, with the corresponding texture point, the tint index, what direction quad faces, and the texture index.

---
My guess is the complexity of the models (or that a render layer can have an empty list) is causing the VBO code to produce a negative number, and it is being passed to a method that can't accept it.

It might be as simple as setting values less then zero to zero, but with the edits done to the render engine I can't even see it to make a better guess.


This is the main bit from your latest.log OptiFine would need in a bug report.
It tells them what the error is, where it happens, and the code path up to the error.

```
[Render thread/ERROR] [net.minecraft.client.renderer.GlDebugTextUtils/]: OpenGL API ERROR: 1281 (GL_INVALID_VALUE error generated. neither <first> nor <count> can be negative.)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL14C.nglMultiDrawArrays(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL14C.glMultiDrawArrays(GL14C.java:153) [lwjgl-opengl-3.2.2.jar:build 10]
	at org.lwjgl.opengl.GL14.glMultiDrawArrays(GL14.java:352) [lwjgl-opengl-3.2.2.jar:build 10]
	at com.mojang.blaze3d.platform.GlStateManager.glMultiDrawArrays(GlStateManager.java:2022) [?:?]
	at net.optifine.render.VboRegion.finishDraw(VboRegion.java:333) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.drawRegion(WorldRenderer.java:2307) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228441_a_(WorldRenderer.java:2228) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1605) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.32.jar:33.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$485/1596278280.call(Unknown Source) [forge-1.16.2-33.0.32.jar:33.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
```

**Comment by GradiusLover2000** [comment]
I have let them know and will get back to you if they require you to change anything.
