### ISSUE TITLE
1.16.2 PlatFormer block placement causes immediate crash

### ISSUE THREAD

**Issue by GradiusLover2000** [ShetiPhian/Localizations-and-Issues#257]
By placing down the platformer block on my forge server, the game immediately crashes.  Here is the exact error trace the server provided (it did not provide any more information)

←[m←[1;31m[15:56:54] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:637) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:832) [?:?] {}
Caused by: java.lang.NullPointerException
        at net.minecraft.entity.Entity.<init>(Entity.java:203) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:Entity.getOnPosition,xf:fml:shetiphiancore:Entity.createRunningParticles,xf:fml:randompatches:RandomPatches Entity Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.item.ItemEntity.<init>(ItemEntity.java:47) ~[?:?] {re:classloading,xf:fml:itemphysic:tick,xf:fml:itemphysic:attack,xf:fml:itemphysic:collide,xf:fml:itemphysic:overrideMethod,pl:runtimedistcleaner:A}
        at shetiphian.core.client.gui.EntityGuiItem.<init>(EntityGuiItem.java:28) ~[?:3.8.1] {re:classloading,pl:runtimedistcleaner:A}
        at shetiphian.core.client.gui.EntityGuiItem.<init>(EntityGuiItem.java:23) ~[?:3.8.1] {re:classloading,pl:runtimedistcleaner:A}
        at shetiphian.core.client.gui.EntityGuiItem.<init>(EntityGuiItem.java:39) ~[?:3.8.1] {re:classloading,pl:runtimedistcleaner:A}
        at shetiphian.core.client.gui.EntityGuiItem.<init>(EntityGuiItem.java:47) ~[?:3.8.1] {re:classloading,pl:runtimedistcleaner:A}
        at shetiphian.platforms.common.tileentity.TileEntityPlatFormer.updateOutput(TileEntityPlatFormer.java:219) ~[?:1.7.2] {re:classloading}
        at shetiphian.platforms.common.tileentity.TileEntityPlatFormer.func_73660_a(TileEntityPlatFormer.java:95) ~[?:1.7.2] {re:classloading}
        at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:366) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        ... 5 more

**Comment by GradiusLover2000** [comment]
I have just updated the mod to 1.7.2**B** and will test again (I concluded this might be the issue via another closed issue here on the git) and will let you know.

please consider making the version number 1.7.3 instead of 1.7.2b, the b is very confusing.

**Comment by ShetiPhian** [comment]
Try this build: http://www.mediafire.com/file/xsi552hc67wpqm6/file

Found another issue while looking into this, the first few Forge builds call a client only method from a common method I was using, which causes a class not found exception on the server.
The new way I'm handling the code is a bit more optimized so that worked out.

**Comment by GradiusLover2000** [comment]
Yep, all fixed here, now is a better time than ever to push to curse

**Comment by ShetiPhian** [comment]
Yep, rather large bug, never good to lock out a world worse whens its a server world.
Need to patch 1.14 and 1.15 also.

You don't need to download again, it will be the same file just renamed "platforms-1.16-1.7.3"

**Comment by ShetiPhian** [comment]
That was quick Curse approval, builds are now available.
