### ISSUE TITLE
Re-entrance detected during prepare phase

### ISSUE THREAD

**Issue by son0fether** [ShetiPhian/Localizations-and-Issues#264]
With just this mod, not any of the mods depending on it, I'm getting the following stacktrace on startup and a crash.

Forge: 33.0.61
Mod: shetiphiancore-1.16-3.8.1.jar
--

Launching target 'fmlclient' with arguments [--version, forge-33.0.61, ...]

Re-entrance detected during prepare phase, this will cause serious problems.
org.spongepowered.asm.mixin.transformer.throwables.ReEntrantTransformerError: Re-entrance error.
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:278)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206)
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135)
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256)
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:140)
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:149)
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112)
	at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:34)
	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:177)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:533)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:151)
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112)
	at cpw.mods.modlauncher.TransformerClassWriter.getSupers(TransformerClassWriter.java:83)
	at cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:66)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1200)
	at org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm.Frame.merge(Frame.java:1197)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:408)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:132)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256)
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:140)
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97)
	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$429/2146303527.buildTransformedClassNodeFor(Unknown Source)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:212)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:200)
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1007)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:997)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:885)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:730)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:646)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206)
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109)
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135)
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$462/691854979.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by ShetiPhian** [comment]
Do you also have Botania or Patchouli?
If so you have the same error as this report: https://github.com/ShetiPhian/Localizations-and-Issues/issues/262

> Its a Mixin crash, but I don't use mixin, Vazkii does for the asm in Botania and Patchouli.
My guess is its a conflict with their mixin asm, and my asm that uses the java script one provided by Forge.

If your not running those mods, then that would indicate the Forge asm system isn't compatible with Mixin asm anymore.

**Comment by son0fether** [comment]
Thanks, yes, I was just about to report that this doesn't happen on a fresh install with just the EnderChest mod and this dependency.  I have Botania + dependency Patcholi.

**Comment by ShetiPhian** [comment]
This is one of those bugs I lack sufficient knowledge to fix.
I don't know the Mixin system at all, nor do I know how the backend of the Forge javascript system works.
