### ISSUE TITLE
Terraqueous has failed to load correctly

### ISSUE THREAD

**Issue by DatrixTHLK** [ShetiPhian/Localizations-and-Issues#275]
Hi there,

The only thing I can think of is that caused this is forge updating to 34.1.32. If you know already then you may ignore it as I just wanted to make sure you knew. Thanks!

**Comment by WenXin20** [comment]
Hello, I updated to forge v34.1.33 and also got this error:
<details>
  <summary>Error Log</summary>
  
  ```
[00:51:37] [modloading-worker-2/ERROR]: Failed to create mod instance. ModID: terraqueous, class shetiphian.terraqueous.Terraqueous
java.lang.ExceptionInInitializerError: null
	at shetiphian.terraqueous.Terraqueous.<init>(Terraqueous.java:54) ~[?:1.7.4]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) [?:34.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3108/1719999141.run(Unknown Source) [?:34.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3422/1010419513.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?]
	at shetiphian.terraqueous.common.worldgen.WorldGenRegistry.<clinit>(WorldGenRegistry.java:79) ~[?:1.7.4]
	... 16 more
  ```
  
</details>

**Comment by ShetiPhian** [comment]
This looks to have fixed it.
Once confirmed I'll push to Curse.

http://www.mediafire.com/file/48tjuqmyl4f8806/terraqueous-1.16-1.7.5--TESTER.jar/file

**Comment by WenXin20** [comment]
Yes, that has fixed it for me, thanks!

**Comment by ShetiPhian** [comment]
Now on Curse:
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/3095470

No need to download again, its the same file just renamed.

**Comment by DatrixTHLK** [comment]
It's fixed! Thanks again for the update and response! I appreciate it.
