### ISSUE TITLE
1.15.2 JEI render ender_tank client crash

### ISSUE THREAD

**Issue by officerwolf** [ShetiPhian/Localizations-and-Issues#289]
step to reproduce crash.
search in JEI: tank, ender, or anytime endertank is rendered to JEI

running a server and it doesnt not crash the server as i know have not tried to place any ender items or chicken loader items
it only crashes client side. 

---- Minecraft Crash Report ----
// There are four lights!

Time: 1/29/21 6:22 AM
Description: Rendering item

java.lang.ExceptionInInitializerError: null
	at codechicken.enderstorage.client.render.tile.RenderTileEnderTank.renderTank(RenderTileEnderTank.java:85) ~[?:1.15.2-2.5.2.164] {re:classloading}
	at codechicken.enderstorage.client.render.item.EnderTankItemRender.renderItem(EnderTankItemRender.java:33) ~[?:1.15.2-2.5.2.164] {re:classloading}
	at codechicken.lib.render.item.CCRenderItem.func_229111_a_(CCRenderItem.java:34) ~[?:1.15.2-3.3.5.407] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:190) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:obfuscate:gui_patch,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:211) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:obfuscate:gui_patch,pl:runtimedistcleaner:A}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:37) ~[?:6.0.0.3] {re:classloading}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:26) ~[?:6.0.0.3] {re:classloading}
	at mezz.jei.render.IngredientListElementRenderer.renderSlow(IngredientListElementRenderer.java:75) ~[?:6.0.0.3] {re:classloading}
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:202) ~[?:6.0.0.3] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:106) ~[?:6.0.0.3] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:113) ~[?:6.0.0.3] {re:classloading}
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:177) ~[?:6.0.0.3] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:82) ~[?:6.0.0.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_824_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:369) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:363) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.render(SourceFile:82) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.47.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/1823438851.call(Unknown Source) [forge-1.15.2-31.2.47.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {re:classloading}
Caused by: java.lang.NullPointerException
	at org.orecruncher.lib.effects.entity.CapabilityEntityFXData$EventHandler.attachCapabilities(CapabilityEntityFXData.java:67) ~[?:1.15.2-1.0.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_208_EventHandler_attachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.1-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:575) ~[?:?] {re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:569) ~[?:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.Entity.<init>(Entity.java:221) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:Entity.getOnPosition,xf:fml:immersiveengineering:IE wire damage,xf:fml:shetiphiancore:Entity.createRunningParticles}
	at net.minecraft.entity.item.ItemEntity.<init>(ItemEntity.java:48) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at codechicken.lib.render.RenderUtils.<clinit>(RenderUtils.java:44) ~[?:1.15.2-3.3.5.407] {re:classloading}
	... 35 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at codechicken.enderstorage.client.render.tile.RenderTileEnderTank.renderTank(RenderTileEnderTank.java:85)
	at codechicken.enderstorage.client.render.item.EnderTankItemRender.renderItem(EnderTankItemRender.java:33)
	at codechicken.lib.render.item.CCRenderItem.func_229111_a_(CCRenderItem.java:34)
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:190)

-- Item being rendered --
Details:
	Item Type: ender_tank
	Registry Name: enderstorage:ender_tank
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:211)
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:37)

-- Ingredient being rendered --
Details:
	Mod Name: EnderStorage
	Registry Name: enderstorage:ender_tank
	Display Name: Ender Tank
	String Name: 1 ender_tank
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:256)
	at mezz.jei.render.IngredientListElementRenderer.renderSlow(IngredientListElementRenderer.java:77)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:202)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:106)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:113)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:177)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:82)
	at net.minecraftforge.eventbus.ASMEventHandler_824_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:369)
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:363)
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.render(SourceFile:82)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/1823438851.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- JEI render details --
Details:
	Unique Id (for Blacklist): enderstorage:ender_tank
	Ingredient Type: class net.minecraft.item.ItemStack
	Error Info: 1 ender_tank enderstorage:ender_tank
	Filter Text: ende
	Edit Mode Enabled: false
	Debug Mode Enabled: false

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.InventoryScreen
	Mouse location: Scaled: (353, 222). Absolute: (707.000000, 445.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Officerwolf'/250, l='MpServer', x=-157.84, y=56.00, z=39.63]]
	Chunk stats: Client Chunk Cache: 729, 523
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 1609358451611968982
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-112,66,48), Chunk: (at 0,4,0 in -7,3; contains blocks -112,0,48 to -97,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3591121 game time, 2069980 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2257231624 bytes (2152 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 24
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.47.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.47
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		CyclopsCore-1.15.2-1.9.0.jar Cyclops Core {cyclopscore@1.9.0 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		SoundControl-1.15.2-1.0.0.1.jar §3Dynamic Surroundings: §eSound Control {sndctrl@1.15.2-1.0.0.1 DONE}
		SimplyJetpacks2-1.15.2-2.5.4.1.jar Simply Jetpacks 2 {simplyjetpacks@1.15.2-2.5.4.1 DONE}
		pamhc2trees-1.15.2-1.0.7.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		gun-mod-0.16.1-1.15.2.jar MrCrayfish's Gun Mod {cgm@0.16.1 DONE}
		dungeon_armors_1.0.0.jar Dungeon Armors {dungeon_armors@1.0.0 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		jei-1.15.2-6.0.0.3.jar Just Enough Items {jei@6.0.0.3 DONE}
		IntegratedTerminals-1.15.2-1.0.16.jar IntegratedTerminals {integratedterminals@1.0.16 DONE, integratedterminalscompat@1.0.16 DONE}
		SlashBlade-1.15-0.0.6.jar Slash Blade {slashblade@0.0.6 DONE}
		tesseract-1.0.17-mc1.15.jar Tesseract {tesseract@1.0.17 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		SilentMechanisms-1.15.2-0.8.0+59.jar Silent's Mechanisms {silents_mechanisms@0.8.0+59 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		mcw-paintings-1.0.0-mc1.15.2.jar Macaw's Paintings {mcwpaintings@1.0.0 DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		appliedenergistics2-7.0.5.jar Applied Energistics 2 {appliedenergistics2@7.0.5 DONE}
		SimpleStorageNetwork-1.15.2-1.0.1.jar Simple Storage Network {storagenetwork@1.15.2-1.0.1 DONE}
		DimStorage-1.15.2-3.1.6.jar DimStorage {dimstorage@3.1.6 DONE}
		buildinggadgets-3.4.1.jar Building Gadgets {buildinggadgets@3.4.1 DONE}
		mcjtylib-1.15-4.1.13.jar McJtyLib {mcjtylib@1.15-4.1.13 DONE}
		rftoolsbase-1.15-1.1.10.jar RFToolsBase {rftoolsbase@1.15-1.1.10 DONE}
		xnet-1.15-2.1.14.jar XNet {xnet@1.15-2.1.14 DONE}
		mcw-doors-1.0.1fix-mc1.15.1-2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		SnowRealMagic-1.15.2-1.8.0.jar Snow! Real Magic! {snowrealmagic@1.8.0 DONE}
		Kiwi-1.15.2-2.8.5.jar Kiwi {kiwi@2.8.5 DONE}
		rftoolspower-1.15-2.2.6.jar RFToolsPower {rftoolspower@1.15-2.2.6 DONE}
		forge-1.15.2-31.2.47-universal.jar Forge {forge@31.2.47 DONE}
		shetiphiancore-1.15-3.7.4.jar ShetiPhian-Core {shetiphiancore@3.7.4 DONE}
		MoreMekanismOres-1.15.2-1.0.5.jar More Mekanism Ores {mmko@1.15.2-1.0.5 DONE}
		scuba-gear-1.15.2-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 DONE}
		refinedstorage-1.8.8.jar Refined Storage {refinedstorage@1.8.8 DONE}
		IntegratedCrafting-1.15.2-1.0.10.jar IntegratedCrafting {integratedcrafting@1.0.10 DONE}
		forge-1.15.2-31.2.47-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-1.0.0.jar CoFH Core {cofh_core@1.0.0 DONE}
		thermal-1.15.2-1.0.2.jar Thermal Series {thermal@1.0.2 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.15.2-2.3.3-e356e61.jar Industrial Foregoing {industrialforegoing@2.3.3 DONE}
		rftoolsutility-1.15-2.1.20.jar RFToolsUtility {rftoolsutility@1.15-2.1.20 DONE}
		Environs-1.15.2-1.0.0.0.jar §3Dynamic Surroundings: §eEnvirons {environs@1.15.2-1.0.0.0 DONE}
		endertanks-1.15-1.8.4.jar EnderTanks {endertanks@1.8.4 DONE}
		CommonCapabilities-1.15.2-2.5.4.jar CommonCapabilities {commoncapabilities@2.5.4 DONE}
		thermal_innovation-1.15.2-1.0.0.jar Thermal Innovation {thermal_innovation@1.0.0 DONE}
		ToolBelt-1.15.2-1.14.2.jar Tool Belt {toolbelt@1.14.2 DONE}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 DONE}
		ImmersiveEngineering-1.15.2-4.1.1-125.jar Immersive Engineering {immersiveengineering@1.15.2-4.1.1-125 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		mcw-trapdors-1.0.0fix-mc1.15.2.jar Macaw's Trapdoors {mcwtrpdoors@1.0.0 DONE}
		SilentGear-1.15.2-1.9.3122.jar Silent Gear {silentgear@1.9.3+122 DONE}
		SuperMultiDrills-1.15.2-2.1.0+4.jar Super Multi-Drills {supermultidrills@2.1.0+4 DONE}
		ChickenChunks-1.15.2-2.5.1.79-universal.jar ChickenChunks {chickenchunks@1.15.2-2.5.1.79 DONE}
		pamhc2foodextended-1.15.2-1.0.0.jar Pam's HarvestCraft 2 Food Extended {pamhc2foodextended@version DONE}
		car-1.15.2-2.0.13.jar Ultimate Car Mod {car@1.15.2-2.0.13 DONE}
		plane-1.15.2-1.0.0.jar Ultimate Plane Mod {plane@1.15.2-1.0.0 DONE}
		rftoolsbuilder-1.15-2.1.16.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.16 DONE}
		SolarFluxReborn-1.15.2-15.2.3.jar Solar Flux Reborn {solarflux@15.2.3 DONE}
		curios-FORGE-1.15.2-2.0.2.7.jar Curios API {curios@FORGE-1.15.2-2.0.2.7 DONE}
		Botania-r1.15-388.jar Botania {botania@r1.15-388 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		IntegratedDynamics-1.15.2-1.1.20.jar IntegratedDynamics {integrateddynamics@1.1.20 DONE, integrateddynamicscompat@1.1.20 DONE}
		rftoolsstorage-1.15-1.1.13.jar RFToolsStorage {rftoolsstorage@1.15-1.1.13 DONE}
		pamhc2foodcore-1.15.2-1.1.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		thermal_cultivation-1.15.2-1.0.2.jar Thermal Cultivation {thermal_cultivation@1.0.2 DONE}
		FluxNetworks-1.15.2-5.0.3-4.jar Flux Networks {fluxnetworks@1.15.2-5.0.3-4 DONE}
		rftoolscontrol-1.15-3.0.9.jar RFToolsControl {rftoolscontrol@1.15-3.0.9 DONE}
		thermal_expansion-1.15.2-1.0.2.jar Thermal Expansion {thermal_expansion@1.0.2 DONE}
		IntegratedTunnels-1.15.2-1.6.14.jar IntegratedTunnels {integratedtunnels@1.6.14 DONE, integratedtunnelscompat@1.6.14 DONE}
		lostcities-1.15-3.0.2-alpha.jar LostCities {lostcities@1.15-3.0.2-alpha DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		obfuscate-0.4.2-1.15.2.jar Obfuscate {obfuscate@0.4.2 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		MekanismTools-1.15.2-9.10.9.422.jar Mekanism: Tools {mekanismtools@9.10.9 DONE}
		mcws-roofs-1.15.2-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		mcw-furniture-2.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@2.0.0 DONE}
		refinedstorageaddons-0.6.3.jar Refined Storage Addons {refinedstorageaddons@0.6.3 DONE}
		CodeChickenLib-1.15.2-3.3.5.407-universal.jar CodeChicken Lib {codechickenlib@3.3.5.407 DONE}
		EnderStorage-1.15.2-2.5.2.164-universal.jar EnderStorage {enderstorage@2.5.2.164 DONE}
		QuantumStorage-1.15.2-5.1.1.jar QuantumStorage {quantumstorage@NONE DONE}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Patchouli open book context: n/a
	Launched Version: 1.15.2-forge-31.2.47
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.09, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor

**Comment by ShetiPhian** [comment]
This is a crash in the EnderStorage mod. (which also has it own version of an Ender Tank)
https://github.com/TheCBProject/EnderStorage/issues
