### ISSUE TITLE
Crash when opening the chest in server

### ISSUE THREAD

**Issue by Panderine** [ShetiPhian/Localizations-and-Issues#328]
**Describe the bug**
When you place the chest and try to open it nothing happens. In the server log I see an error:

`[16:55:38] [Server thread/FATAL]: Error executing task on Server

java.lang.NoClassDefFoundError: net/minecraft/class_1074

	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]

	at shetiphian.enderchests.common.misc.ChestInfoHelper.localize(ChestInfoHelper.java:64) ~[enderchests-%5Bfabric%5D-1.18-1.0.2.jar:?]

	at shetiphian.enderchests.common.misc.ChestInfoHelper.formatChestOwner(ChestInfoHelper.java:53) ~[enderchests-%5Bfabric%5D-1.18-1.0.2.jar:?]

	at shetiphian.enderchests.common.inventory.ContainerEnderChest.common_setup(ContainerEnderChest.java:47) ~[enderchests-%5Bfabric%5D-1.18-1.0.2.jar:?]

	at shetiphian.enderchests.common.inventory.ContainerEnderChest.<init>(ContainerEnderChest.java:33) ~[enderchests-%5Bfabric%5D-1.18-1.0.2.jar:?]

	at shetiphian.enderchests.common.inventory.ContainerProviders$EnderChest.createMenu(ContainerProviders.java:42) ~[enderchests-%5Bfabric%5D-1.18-1.0.2.jar:?]

	at net.minecraft.server.network.ServerPlayerEntity.openHandledScreen(ServerPlayerEntity:1032) ~[?:?]

	at shetiphian.enderchests.common.block.BlockEnderChest.onBlockActivated(BlockEnderChest.java:176) ~[enderchests-%5Bfabric%5D-1.18-1.0.2.jar:?]

	at shetiphian.enderchests.common.block.BlockEnderChest.onUse(BlockEnderChest.java:162) ~[enderchests-%5Bfabric%5D-1.18-1.0.2.jar:?]

	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]

	at net.minecraft.server.network.ServerPlayerInteractionManager.redirect$bck000$activateWithOptionalCactus(ServerPlayerInteractionManager:1529) ~[?:?]

	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]

	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1057) ~[?:?]

	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]

	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]

	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]

	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]

	at net.minecraft.util.thread.ThreadExecutor.redirect$zlg000$redirectExecuteTask(ThreadExecutor:521) ~[?:?]

	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]

	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:11748) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[server-intermediary.jar:?]

	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]

	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.handler$zpm000$modifiedRunLoop(MinecraftServer:4865) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663) ~[server-intermediary.jar:?]

	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]

	at java.lang.Thread.run(Thread.java:833) [?:?]

Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1074

	... 26 more
`

**Additional context**
Minecraft Version:  1.18.1
Forge Version:  FABRIC
ShetiPhian Core Version: 1.2.2
My Mod(s) Name & Version: EnderChest (Fabric) 1.0.2
Are other mods present?
If yes:
- Does everything work without my mods?
- Have you tested with only my mods?

PasteBin or GitHub Gists links
latest.log = 
debug.log =

**Comment by ShetiPhian** [comment]
Now that's interesting.
Running the server in dev mode a try/catch is enough to stop that crash.

But in a standard user environment the try/catch is ignored...
rather then the code fully running in the try/catch block, it must be loading classes outside of it then running the rest inside.

That actually makes an error I had a few years ago make since.

Give this build a try:
https://www.mediafire.com/file/fhgnbtv9hzeu0ux/enderchests-%255Bfabric%255D-1.18-1.0.3--TESTER.jar/file

**Comment by Panderine** [comment]
that fixed it :D

**Comment by ShetiPhian** [comment]
Pushed the build to Curse.
No need to redownload, only suggest removing tester from the file name
