### ISSUE TITLE
shetiphiancore-[fabric]-1.18-1.2.6 prevents some resource packs from loading

### ISSUE THREAD

**Issue by Stelk** [ShetiPhian/Localizations-and-Issues#338]
**Describe the bug**
Loading Resource Packs with spaces within the compressed filenames will result in an error and the Resource Pack will not be loaded.  Specifically Lithos+v1.57+for+1.18x will not load when shetiphiancore-[fabric]-1.18-1.2.6 is present.

`(v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, ShetiPhianCore), Lithos+v1.57+for+1.18x.zip
[08:07:38] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:models/block/wood/original dark oak door.zip
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:models/block/wood/original dark oak door.zip
	at net.minecraft.class_2960.<init>(class_2960.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_3258.method_14408(class_3258.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_3294.method_14488(class_3294.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_6861.method_14488(class_6861.java:80) ~[client-intermediary.jar:?]
	at dev.monarkhes.myron.impl.client.Myron.lambda$onInitializeClient$4(Myron.java:54) ~[myron-1.6.2+1.18.1-4a48e4f279872f0a.jar:?]
	at net.fabricmc.fabric.impl.client.model.ModelLoadingRegistryImpl$LoaderInstance.onModelPopulation(ModelLoadingRegistryImpl.java:84) ~[fabric-models-v0-0.3.6+d7c144a860-7228847ad834dd9d.jar:?]
	at net.minecraft.class_1088.handler$zeh000$addModelHook(class_1088.java:1167) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_4727(class_1088.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.<init>(class_1088.java:193) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18178(class_1092.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_18789(class_1092.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
`

**Additional context**
Minecraft Version: 1.18.2
Fabric Version: Fabric Loader 0.13.3
Resource Pack Example: Lithos+v1.57+for+1.18x
ShetiPhian Core Version:  shetiphiancore-[fabric]-1.18-1.2.6
My Mod(s) Name & Version:  shetiphiancore-[fabric]-1.18-1.2.6
Are other mods present? **YES**
If yes:
- Does everything work without my mods? **YES**
- Have you tested with only my mods? **YES**

PasteBin or GitHub Gists links
latest.log = 
debug.log =

**Comment by ShetiPhian** [comment]
Looks to be when [Myron](https://github.com/Haven-King/myron) tries to load the file.
The bug would need to be reported there, then once fixed I can bundle the new version.

Until then can you load the resource pack by replacing the spaces with underscores?
