### ISSUE TITLE
Crash - possible Mystcraft conflict

### ISSUE THREAD

**Issue by hoolatehip** [ShetiPhian/Localizations-and-Issues#376]
Crash every few seconds on a new world. Only appears to be a problem in superflat. 

**Additional context**
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2860
ShetiPhian Core Version: 3.5.9
My Mod(s) Name & Version: Terraqueous 1.4.17b
Are other mods present? Yes
If yes:
- Does everything work without my mods? Yes
- Have you tested with only my mods? No

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  Botania Tweaks Core (botaniatweaks-1.9.1.jar)
  NothiriumPlugin (Nothirium-1.12.2-0.1.4-beta.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.5.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ReplantFMLLoadingPlugin (replant1.12.2-1.0.0.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  RenderLibPlugin (RenderLib-1.12.2-1.0.8.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-0.2.11.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.4.1.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_22.15.1_Forge_1.12.jar)
  EntityCullingPlugin (EntityCulling-1.12.2-6.0.2.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.28.0_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 10/14/22 3:23 PM
Description: Exception in server tick loop

java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at shetiphian.terraqueous.common.worldgen.GenFlowers.generate(GenFlowers.java:54)
	at shetiphian.terraqueous.common.worldgen.GenBase.generate(GenBase.java:68)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:305)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:376)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:198)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3025_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ShetiPhian** [comment]
1.12 hasn't been supported for years.
I don't remember what generation config options where available then but the two that may be a help is disabling generation in flat worlds and the dimension blacklist. The final option would be to disable the flower generation, I believe they are found via bonemeal in that version.
