### ISSUE TITLE
Forge 1.19.2: Using bone meal causes lag spike (possible incompatibility)

### ISSUE THREAD

**Issue by Daltaxy** [ShetiPhian/Localizations-and-Issues#407]
**Describe the bug**

https://user-images.githubusercontent.com/111076631/227808249-fddebc16-39e7-4863-a229-f50c7d9b5e0d.mp4

Hello. Using bone meal (right click) in my world causes a lag spike and it is very hard to grow things with it, as it often will not use it even after the lag
I initially used spark to find the source. https://spark.lucko.me/55wBvNc7nc
this profile is linked to the latest logs also included here
![image](https://user-images.githubusercontent.com/111076631/227808303-85e97c4b-8b43-45d1-b279-321c5d072a2f.png)

<details><summary>Details about the profile</summary>
<p>

![image](https://user-images.githubusercontent.com/111076631/227808586-56a23293-54cc-4757-9e59-b3033d949dc0.png)

</p>
</details> 

**Additional context**
Minecraft Version: 1.19.2
Forge Version: 43.2.8
ShetiPhian Core Version: shetiphiancore-forge-1.19.0-3.11.3.01

My Mod(s) Name & Version: 
Are other mods present?
If yes:
- Does everything work without my mods?
- yes
- Have you tested with only my mods?
- no

PasteBin or GitHub Gists links
I cut the logs because they are too heavy.
latest.log = https://gist.github.com/Daltaxy/e5b4eaa758911e860b0b6f4a1e668822
debug.log = https://gist.github.com/Daltaxy/ae7f55c399800971eb3558c8b7dd9531

**Comment by ShetiPhian** [comment]
Something is going wrong,
While a small bit of leg on first use is expected in large packs, it shouldn't happen again for that session.
I know why though; On use I check if my lookup table is empty and if so generate it. Normally at bare minimum the vanilla entries get generated so its never empty after the first use.
The leg spike happening every time indicates the list is always empty, so something is causing even the vanilla entries from being generated. 
If I used a first run check instead, even when the lookup fails to generate the spike would be limited to the first use.


As for the root cause;
Looks like the largest amount of time is spent with the Forge event bus error handler.
So something is throwing an error when the vanilla diamond axe is used to strip logs.

In the pack your using what happens if to try to strip a log with the vanilla diamond axe?

**Comment by Daltaxy** [comment]
> Something is going wrong, While a small bit of leg on first use is expected in large packs, it shouldn't happen again for that session. I know why though; On use I check if my lookup table is empty and if so generate it. Normally at bare minimum the vanilla entries get generated so its never empty after the first use. The leg spike happening every time indicates the list is always empty, so something is causing even the vanilla entries from being generated. If I used a first run check instead, even when the lookup fails to generate the spike would be limited to the first use.
> 
> As for the root cause; Looks like the largest amount of time is spent with the Forge event bus error handler. So something is throwing an error when the vanilla diamond axe is used to strip logs.
> 
> In the pack your using what happens if to try to strip a log with the vanilla diamond axe?

so... I removed the mods that were causing trouble. "Dungeons Mobs" and "Dungeons Libraries"
Removing these fixed the issue.
As for stripping logs, I just tried without the two mods and it worked fine.
I will reenable them and try with them right now

**Comment by Daltaxy** [comment]
still no lag after stripping, in spite of enabling the two mods
profiler: https://spark.lucko.me/ZYWPCzyh9r
I stripped some logs first, then grabbed bone meal from a chest and reproduced the lag spike.
debug.log:  https://gist.github.com/Daltaxy/67b8272028c8c5a8512fc56ff4ea347f

**Comment by ShetiPhian** [comment]
I missed it in the stacktrace before, but I see what's happening now.

Dungeons Mobs is not checking for null before trying to use the player variable in their EntityEvents.preventBlockInteraction.
This is causing a Null Pointer Exception on every attempted lookup, and when combined with my error of thinking the vanilla entries would always get generated, results in bonemeal being unusable.


Future builds of ShetiPhianCore will handle this better, but for now if you disable the "bonemeal_restores_bark" config option the lookup generation code will be skipped and bonemeal will work without needing to remove any mods.

**Comment by Daltaxy** [comment]
> I missed it in the stacktrace before, but I see what's happening now.
> 
> Dungeons Mobs is not checking for null before trying to use the player variable in their EntityEvents.preventBlockInteraction. This is causing a Null Pointer Exception on every attempted lookup, and when combined with my error of thinking the vanilla entries would always get generated, results in bonemeal being unusable.
> 
> Future builds of ShetiPhianCore will handle this better, but for now if you disable the "bonemeal_restores_bark" config option the lookup generation code will be skipped and bonemeal will work without needing to remove any mods.

cheers! I'll do that now.

**Comment by ShetiPhian** [comment]
In the latest builds the code is more fault-tolerant, this shouldn't happen anymore.

**Comment by WenXin20** [comment]
Hi, I'm using ShetiphianCore v3.11.3.04, and this issue with Dungeons Mobs seems to be back again. It completey froze my game when attempting to use bonemeal

```[12Jul2023 11:12:45.707] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.player.Player.m_21023_(net.minecraft.world.effect.MobEffect)" because "owner" is null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class com.legacy.blue_skies.events.SkiesPlayerEvents onToolUse(Lnet/minecraftforge/event/level/BlockEvent$BlockToolModificationEvent;)V
		2: ASM: class com.infamous.dungeons_mobs.entities.EntityEvents preventBlockInteraction(Lnet/minecraftforge/event/level/BlockEvent$BlockToolModificationEvent;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$1484/0x00000008007f6d98@43db6e68
		4: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge toolModification(Lnet/minecraftforge/event/level/BlockEvent$BlockToolModificationEvent;)V
		5: ASM: class vazkii.quark.base.handler.ToolInteractionHandler toolActionEvent(Lnet/minecraftforge/event/level/BlockEvent$BlockToolModificationEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1484/0x00000008007f6d98@78ca4901
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_21023_(net.minecraft.world.effect.MobEffect)" because "owner" is null
	at TRANSFORMER/dungeons_mobs@1.19.2-4.0.8-beta/com.infamous.dungeons_mobs.entities.EntityEvents.preventBlockInteraction(EntityEvents.java:88)
	at TRANSFORMER/dungeons_mobs@1.19.2-4.0.8-beta/com.infamous.dungeons_mobs.entities.__EntityEvents_preventBlockInteraction_BlockToolModificationEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.7/net.minecraftforge.event.ForgeEventFactory.onToolUse(ForgeEventFactory.java:326)
	at TRANSFORMER/forge@43.2.7/net.minecraftforge.common.extensions.IForgeBlockState.getToolModifiedState(IForgeBlockState.java:660)
	at TRANSFORMER/shetiphiancore@3.11.3.04/shetiphian.core.internal.EventHandler.lambda$onApplyBonemeal$1(EventHandler.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/shetiphiancore@3.11.3.04/shetiphian.core.internal.EventHandler.onApplyBonemeal(EventHandler.java:72)
	at TRANSFORMER/shetiphiancore@3.11.3.04/shetiphian.core.internal.__EventHandler_onApplyBonemeal_BonemealEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.7/net.minecraftforge.event.ForgeEventFactory.onApplyBonemeal(ForgeEventFactory.java:332)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:66)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.BoneMealItem.m_6225_(BoneMealItem.java:36)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:237)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:252)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:237)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:352)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.redirect$dpo000$onDoItemUse(Minecraft.java:15458)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1953)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1768)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.7/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)```

**Comment by Daltaxy** [comment]
> disable the "bonemeal_restores_bark" config option

hello, have you tried to disable the "bonemeal_restores_bark" config option, as mentioned by the maker in the previous answers?

**Comment by Daltaxy** [comment]
> Hi, I'm using ShetiphianCore v3.11.3.04, and this issue with Dungeons Mobs seems to be back again. It completey froze my game when attempting to use bonemeal
> 
> ```
> 	Index: 2
> 	Listeners:
> 		0: NORMAL
> 		1: ASM: class com.legacy.blue_skies.events.SkiesPlayerEvents onToolUse(Lnet/minecraftforge/event/level/BlockEvent$BlockToolModificationEvent;)V
> 		2: ASM: class com.infamous.dungeons_mobs.entities.EntityEvents preventBlockInteraction(Lnet/minecraftforge/event/level/BlockEvent$BlockToolModificationEvent;)V
> 		3: net.minecraftforge.eventbus.EventBus$$Lambda$1484/0x00000008007f6d98@43db6e68
> 		4: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge toolModification(Lnet/minecraftforge/event/level/BlockEvent$BlockToolModificationEvent;)V
> 		5: ASM: class vazkii.quark.base.handler.ToolInteractionHandler toolActionEvent(Lnet/minecraftforge/event/level/BlockEvent$BlockToolModificationEvent;)V
> 		6: net.minecraftforge.eventbus.EventBus$$Lambda$1484/0x00000008007f6d98@78ca4901
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_21023_(net.minecraft.world.effect.MobEffect)" because "owner" is null
> 	at TRANSFORMER/dungeons_mobs@1.19.2-4.0.8-beta/com.infamous.dungeons_mobs.entities.EntityEvents.preventBlockInteraction(EntityEvents.java:88)
> 	at TRANSFORMER/dungeons_mobs@1.19.2-4.0.8-beta/com.infamous.dungeons_mobs.entities.__EntityEvents_preventBlockInteraction_BlockToolModificationEvent.invoke(.dynamic)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
> 	at TRANSFORMER/forge@43.2.7/net.minecraftforge.event.ForgeEventFactory.onToolUse(ForgeEventFactory.java:326)
> 	at TRANSFORMER/forge@43.2.7/net.minecraftforge.common.extensions.IForgeBlockState.getToolModifiedState(IForgeBlockState.java:660)
> 	at TRANSFORMER/shetiphiancore@3.11.3.04/shetiphian.core.internal.EventHandler.lambda$onApplyBonemeal$1(EventHandler.java:74)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at TRANSFORMER/shetiphiancore@3.11.3.04/shetiphian.core.internal.EventHandler.onApplyBonemeal(EventHandler.java:72)
> 	at TRANSFORMER/shetiphiancore@3.11.3.04/shetiphian.core.internal.__EventHandler_onApplyBonemeal_BonemealEvent.invoke(.dynamic)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
> 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
> 	at TRANSFORMER/forge@43.2.7/net.minecraftforge.event.ForgeEventFactory.onApplyBonemeal(ForgeEventFactory.java:332)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:66)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.BoneMealItem.m_6225_(BoneMealItem.java:36)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:237)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:252)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:237)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:352)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.redirect$dpo000$onDoItemUse(Minecraft.java:15458)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1953)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1768)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
> 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.7/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
> 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)```
> ```

hello, have you tried to disable the "bonemeal_restores_bark" config option, as mentioned by the maker in the previous answers?

**Comment by ShetiPhian** [comment]
Dungeons Mobs has forgotten the null check.
BlockToolModificationEvent.getPlayer() is Nullable, and needs to be checked before using the returned value.
They also might want to look over the other events, as others might be nullable also (or just add a check to all of them)
