### ISSUE TITLE
"Failed to handle packet" when right-clicking on MultiBeds bed at night

### ISSUE THREAD

**Issue by andreea-mgh** [ShetiPhian/Localizations-and-Issues#418]
**Describe the bug**
When right-clicking a bed from MultiBeds at night nothing happens. The output log just spits this every time I try:

```
Failed to handle packet net.minecraft.class_2885@eaf7f44, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657$class_1658.method_19206()" because "$$1" is null
	at net.minecraft.class_2244.method_19283(class_2244.java:117)
	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43)
	at net.minecraft.class_2244.method_9534(class_2244.java:116)
	at shetiphian.multibeds.common.block.BlockMultiBedBase.method_9534(BlockMultiBedBase.java:209)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_3225.method_14262(class_3225.java:338)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Also when I click during daytime the error doesn't come up but there is no "You can only sleep at night" message anywhere.

**Additional context**
Minecraft Version: 1.19.2
Fabric Version: 0.14.22
ShetiPhian Core Version: shetiphiancore-fabric-1.19.2-1.3.11
Mod Name & Version: multibeds-fabric-1.19.2-1.3.6

**Have you tested with only my mods?**
Yes, it works without the rest of the mods. The mod list is pretty big tho. CurseForge shows 118 mods, including the Fabric API itself. I don't know how to get a full list of those mods but this is what the output log gave: https://pastebin.com/Et7rH8HP

```
Failed to handle packet net.minecraft.class_2885@eaf7f44, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657$class_1658.method_19206()" because "$$1" is null
	at net.minecraft.class_2244.method_19283(class_2244.java:117)
	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43)
	at net.minecraft.class_2244.method_9534(class_2244.java:116)
	at shetiphian.multibeds.common.block.BlockMultiBedBase.method_9534(BlockMultiBedBase.java:209)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:964)
	at net.minecraft.class_3225.method_14262(class_3225.java:338)
	at net.minecraft.class_3244.method_12046(class_3244.java:1145)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ShetiPhian** [comment]
By the looks of it normal beds should fail also.
My beds extend the originals, and sleeping is handled by the original beds.

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657$class_1658.method_19206()" because "$$1" is null
	at net.minecraft.class_2244.method_19283(class_2244.java:117)
	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43)
	at net.minecraft.class_2244.method_9534(class_2244.java:116)
	at shetiphian.multibeds.common.block.BlockMultiBedBase.method_9534(BlockMultiBedBase.java:209)
```

So we're starting in my beds onUse method but since its not being customized it continues to the vanilla onUse method.
The 'ifLeft' is in this block of code
```
player.trySleep(pos).ifLeft((reason) -> {
	if (reason.getMessage() != null) {
		player.sendMessage(reason.getMessage(), true);
	}
});
```
Which indicates 'reason' is null thus the crash when trying to use 'getMessage()'
Meaning something is edited in the trySleep code path; making the changes in one of these:
- ServerPlayerEntity.trySleep : success path
- PlayerEntity.trySleep
- LivingEntity.sleep

After a quick look at the mod names, nothing stood out as a sleep altering mod.
Fabric lacks a debug.log, and doesn't log loaded mixins into the regular one.
With so many mods, unless you know what ones do stuff on sleep, the fastest way to hunt the problem down is to create a two new instances with only half of mods in each. The one with the bug gets its modlist split again. With a list that big you'll probably need to split 6-7 times to get down to a small enough group to pull out one at at time.

**Comment by andreea-mgh** [comment]
Oh, you're right. I thought it was only MultiBeds since two weeks ago I slept in the same world on a normal bed to set my spawnpoint and had no problems. It could be a broken mod update as all beds seem to be broken now. Most likely not actually related to MultiBeds since the problem persists without it. I'll test the rest of the mods and report it on the appropriate mod page then.
