### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by fluor4te** [ShetiPhian/Localizations-and-Issues#442]
Crash on startup
It crashes when minecraft is almost loaded
Without shetiphiancore and terraqueous it doesn't crash

**Additional context**
Minecraft Version: 1.20.1
Forge Version: null (i use fabric 0.15.11)
shetiphiancore 1.20.1-1.2
terraqueous 1.20.1-1.4

PasteBin or GitHub Gists links
latest.log = https://mclo.gs/7P4zcMj

**Comment by ShetiPhian** [comment]
Don't know why its crashing only with my mods in as the stacktrace indicates other mods.

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8608()" because "world" is null
	at dev.emi.trinkets.api.TrinketsApi.getEntitySlots(TrinketsApi.java:124) ~[trinkets-3.7.2.jar:?]
	at dev.emi.trinkets.api.TrinketsApi.getEntitySlots(TrinketsApi.java:134) ~[trinkets-3.7.2.jar:?]
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.update(LivingEntityTrinketComponent.java:64) ~[trinkets-3.7.2.jar:?]
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.<init>(LivingEntityTrinketComponent.java:44) ~[trinkets-3.7.2.jar:?]
	...
	at net.minecraft.entity.decoration.ArmorStandEntity.<init>(ArmorStandEntity.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.entity.decoration.ArmorStandEntity.<init>(ArmorStandEntity.java:106) ~[client-intermediary.jar:?]
	at dev.kikugie.elytratrims.client.render.ETItemRenderer.render(ETItemRenderer.kt:22) ~[elytratrims-fabric-3.1.7+1.20.1.jar:?]
	at net.minecraft.client.render.item.ItemRenderer.handler$ded000$elytratrims$renderElytraItem(ItemRenderer.java:1019) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.item.ItemRenderer.renderItem(ItemRenderer.java:125) ~[client-intermediary.jar:?]
```

---

There is a bunch of issues in the pack, that may be caused by these conflicts:

```
- Mod 'Expanded Ecosphere' (expanded_ecosphere) 3.2.4 conflicts with any version of mod 'William Wythers' Overhauled Overworld' (wwoo), which is present with the following versions: 2.0.0!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Expanded Ecosphere' (expanded_ecosphere) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
```

```
- Mod 'Peek' (peek) 1.20.1-1.3.1 conflicts with any version of mod 'Enhanced Block Entities' (enhancedblockentities), which is present with the following versions: 0.9+1.20!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Peek' (peek) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
```

---

Another issue: "Iris is present, custom block renders will not work" 
That is breaking the following Model Loaders

```
'terraqueous:composite', 'terraqueous:pergola', 'terraqueous:multi-layer'
'supplementaries:blackboard', 'supplementaries:book_pile', 'supplementaries:bunting', 'supplementaries:faucet', 'supplementaries:flower_box', 'supplementaries:goblet', 'supplementaries:frame_block', 'supplementaries:mimic_block', 'supplementaries:rope_knot'
'amendments:carpet_overlay', 'amendments:cauldron', 'amendments:hanging_pot', 'amendments:waterlogged_lily', 'amendments:tool_hook', 'amendments:wall_lantern'
'fastpaintings:painting'
```

There is likely a companion mod that fixes this (Indium fixes Sodium breaking custom models)

---

My plant mixins conflict with fabricators_of_create, but looks like we add the same methods so it may work fine.
Even if it doesn't I think only my planters will fail to function.

**Comment by fluor4te** [comment]
oh, i didn't notice that i should update a few mods, sorry for disturbing
