### ISSUE TITLE
crash log 

### ISSUE THREAD

**Issue by MrSkully1** [ShetiPhian/Localizations-and-Issues#73]
Fixed the problem just needed update to core

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  Augmented Interactions (auginter-1.0.0-1.11.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.0.jar)
  BetterFoliageLoader (BetterFoliage-1.11.2-Universal.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 5/16/17 7:02 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Platforms (platforms)
Caused by: java.lang.NoClassDefFoundError: shetiphian/platforms/common/tileentity/TileEntityTypeBase
	at shetiphian.platforms.Registry.registerBlocks(Registry.java:27)
	at shetiphian.platforms.Registry.doRegistration(Registry.java:19)
	at shetiphian.platforms.Platforms.preInit(Platforms.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:268)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: shetiphian.platforms.common.tileentity.TileEntityTypeBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: shetiphian/core/common/tileentity/TileEntityFacingBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more
Caused by: java.lang.ClassNotFoundException: shetiphian.core.common.tileentity.TileEntityFacingBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 356697792 bytes (340 MB) / 1111519232 bytes (1060 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2228 Optifine OptiFine_1.11.2_HD_U_B8 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2228.jar) 
	UCH	forge{13.20.0.2228} [Minecraft Forge] (forge-1.11.2-13.20.0.2228.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCH	aether_legacy{v1.4.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.jar) 
	UCH	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.0.1.jar) 
	UCH	auginter{1.0.0} [Augmented Interactions] (auginter-1.0.0-1.11.2.jar) 
	UCH	betterfoliage{2.1.4} [Better Foliage] (BetterFoliage-1.11.2-Universal.jar) 
	UCH	drpcore{0.2.0b} [Dark Roleplay Core] (Dark Roleplay Core Alpha-0.2.0b.jar) 
	UCH	drpmedieval{0.1.7b} [Dark Roleplay Medieval] (Dark Roleplay Medieval 0.1.7c.jar) 
	UCH	props{2.4.1} [Decocraft] (Decocraft-2.4.1_1.11.2.jar) 
	UCH	dooglamoocitiesmod{1.5.0} [Dooglamoo Cities] (dooglamoocitiesmod-1.11.2-1.5.0.jar) 
	UCH	enhancedvisuals{1.0} [Enhanced Visuals] (EnhancedVisuals v1.0.12 mc1.11.2.jar) 
	UCH	hcmw{1.0} [Homecraft Mineware] (HCMW-1.11.2-Universal.jar) 
	UCH	examplemod{1.0} [examplemod] (Joypad-Mod-1.11.2.jar) 
	UCH	joypadsplitscreenmod{1.10.0-0.22} [Joypad / SplitScreen Mod] (Joypad-Mod-1.11.2.jar) 
	UCH	levels{3.0.0} [Levels 3] (Levels 3-1.11.2-Beta.jar) 
	UCH	shetiphiancore{3.4.0} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.0.jar) 
	UCE	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCH	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
Augmented Interactions (auginter-1.0.0-1.11.2.jar)
  com.pau101.auginter.client.asm.AugInterClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.0.jar)
  shetiphian.core.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-1.11.2-Universal.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.162.4' Renderer: 'Radeon (TM) RX 480 Graphics'
	OptiFine Version: OptiFine_1.11.2_HD_U_B8
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-v11.0.zip
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.162.4
	OpenGlRenderer: Radeon (TM) RX 480 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by MrSkully1** [comment]
nevermind just needed update to shetiphiancore

**Comment by ShetiPhian** [comment]
Update ShetiPhianCore, your version is too low.
Something breaks the Forge check, causing dependencies to appear fulfilled when they are not.

This is the first small pack I've seen the issue on. I've only had the issue reported on very large packs, and could reproduce on those packs, but not in small pack. 

Side note:
Joypad-Mod is bundling the examplemod with their own, this may cause issues.
