### ISSUE TITLE
NPE Crash hile Rendering Terraqueous Block

### ISSUE THREAD

**Issue by Zarepheth** [ShetiPhian/Localizations-and-Issues#89]
While playing the game, I was going about my business when the game crashed. From the stack trace, it appears that something from Terraqueous was being tessellated while rending, but a Null Point Exception occurred crashing the game.

Minecraft: 1.12
Forge: 14.21.1.2397
Terraqueous: 1.4.0.1
ShetiPhian-Core: 3.5.0.1

```
Description: Tesselating block model

java.lang.NullPointerException: at index 0
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:236)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:220)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:347)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:257)
	at shetiphian.core.forgefixes.OBJModel$OBJState.getShownConfigs(OBJModel.java:1291)
	at shetiphian.core.forgefixes.OBJModel$OBJBakedModel.func_188616_a(OBJModel.java:1523)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:115)
	...
```

[Log File on paste.ee](https://paste.ee/p/RX9gP)

**Comment by ShetiPhian** [comment]
I'm surprised that code had made it this far needing only a few hacks. It was a unfinished 1.9 rewrite of the 1.8 OBJ loader for Forge but they changed the whole system. (I didn't use it though as it had a bug/missing function, making it unusable for me)
I'll see if I can go back to the Forge one, and if not I'll replace my current system with one based on the new Forge code.

**Comment by ShetiPhian** [comment]
Updates 'shetiphiancore-1.12.0-3.5.0.2' & 'terraqueous-1.12.0-1.4.0.2' should solve this issue.
Please post here if it does not.
